### ISSUE TITLE
Nominate a new chairperson for CommComm

### ISSUE THREAD

**Issue by nebrius** [nodejs/community-committee#113]
As I mentioned to the other CommComm members privately, and as I [detailed in a blog post](https://medium.com/@nebrius/why-im-leaving-the-node-js-project-bff946845a77), I am stepping down as chairperson of CommComm. I fully intend to stay on until a new chairperson has been elected, and I have had a chance to onboard them.

If you are interested in running for this position, please state your interest here. I will be on vacation and without Internet starting Thursday August 24th through Tuesday September 5th.

I would like to propose a nomination deadline of September 8th, following by an election starting Monday September 11th, to be concluded before the September 14th CommComm meeting where we can officially begin the onboarding process for the new chairperson.

It's been an honor working with you all, and I wish you all the best going forward.

**Comment by nebrius** [comment]
Oh, and if anyone has any questions about the position, please feel free to ask me either here or privately over Twitter DM/email.

**Comment by rachelnicole** [comment]
Thanks for all the work you've done Bryan, you've been a great help!!!!

I also would like to nominate myself for the position of chairperson of CommComm.

**Comment by bnb** [comment]
You've done a _ton_ of work for the CommComm in such a short time, Bryan - thank you for **all** of it. 🙏

I'd also like to nominate myself for the position of chairperson.

Node.js is really how I've gotten started in tech, and it's deeply important to me. From the work I've been able to put in to the Evangelism WG over the last few years, enabling people to come to Node.js and become a part of the community. There is so much ground that Node.js has to cover in terms of community, accessibility, and inclusivity - both small changes, and huge efforts. 

There's a lot in the future for Node.js, still - the upcoming Node.js certification, grassroots community efforts like NodeTogether, and the work that can and _needs_ to be done around expanding the openness and community side of the project.

I _deeply_ care about Node.js, and am committed to helping The Community grow as a whole to be an open, safe, and welcoming environment.

**Comment by flickz** [comment]
Thanks for all the work you've done Bryan. Good look with future endeavor.

**Comment by avinassh** [comment]
@nebrius Are there are any requirements for this position? Like

- Age
- Contributions to Node
- Previous experience being in similar roles

**Comment by hijara** [comment]
@avinassh yes. I've listed them as follows -

 - [ ] You need to have multiple blogs on diversity
 - [ ] a twitter account where you regularly bash others who don't share your viewpoint
 - [ ] You must not have a single technical contribution to this project and should have minimal amount of contribution
 - [ ] No experience with nodejs is required whatsoever apart from bringing in a single .md file to a repo
 - [ ] No experience with previous roles are required whatsoever
 - [ ] Males are strictly not allowed to participate
 - [ ] You shall be excellent at locking controversial posts at slight sight of any person bringing logic to the arguments.
 - [ ] If a person, who happens to share his set of ideologies with yours, makes a snarky comment or something distressful, you shall offer your set of best emojis to show your support. However if that person does not, you shall throw the biggest tantrums seen in the wild and ask your peers and their relatives to be highly vocal on social media and to paint him as the most vile person that ever lived on this planet earth.
 - [ ] You shall hate people who don't believe with your ideologies and ask them to kill themselves occasionally (also you shall delete those posts when asked upon such behavior).
 - [ ] But you should also consider everyone equal :)

Let's see how fast does this post gets edited or removed for merely stating the facts I've closely experienced with this community. Be sure to take a screenshot or archive.is before it is removed 😉 .

> “The “social justice” movement is not at all about social justice, but about relentlessly bullying anyone who does not subscribe to their Stalinist ideology.”
> ― Joshua Goldberg

**Comment by RichardLitt** [comment]
@hijara I'm sorry you feel that way. But thank you for your input. You're right, we could do more to be inclusive. We always can. 

I disagree with a few of the points you make, and don't think that they represent the community committee, even from a negative perspective. Instead of deleting your post, I'm commenting here, because otherwise, you're right, I think we're stifling discussion in the name of keeping everybody safe and happy. I don't agree with that kind of moderation, and my normal response has been to step back and say nothing when I see it happen. I haven't raised my voice, most of the time, because I don't think it would be perceived well to say that I think that the natural way for conversations to flow is to fork and change, and to assume they have to be on topic is unrealistic and damaging to communication. 

Here is what I disagree with. I'll keep this short and to the point, because I want to emphasize that, while I understand the place you're coming from, I think that you're taking it a bit far. 

- I don't have multiple blogs about diversity. I don't have a single one, as far as I know, although I do talk about it. 
- I don't try to bash people on Twitter. In fact, I limit my twitter account because I don't like seeing other people bashing each other, either. I think you'll find this is fairly common. 
- Node is a large community. I haven't contributed to core, AFAIK. But I, as a node developer with dozens of npm packages, have a steak in the direction of node, too. You don't have to be a core contrib to be on this committe.
- Most of my work actually _is_ in markdown files, but that doesn't mean I don't know how to get down into the .js files like a stereotypical "node" developer. Belittling documentation isn't really a useful standpoint for you to take.
- There are a lot of males here, and they're welcome. I've got a load of testosterone, buddy. Doesn't mean I can't be on this committee. Who cares what sex you are - what's important is that you're welcoming of others, regardless of theirs.
- I feel you about locking. Often, it's because the maintainers here have ideas about single-threading conversations. It's trivial to open another thread, most of the time, if you're being civil. I would try that, next time, as a good strategy? 
- I disagree with you, and I'm not going to be throwing a tantrum, or talking about it, or calling you a troll. There are a lot of people who follow this way of talking, too. Not everything ends in a twitter fight. Some arguments do escalate, it's true. But to say that you've got to escalate everything to be on this committee? Come on, man. 
- Please stay alive. Everyone, please stay alive. Hell, I think even Trump should stay alive (but not in a position of power). 
- Equality doesn't mean I have to be nice to you. Respect does. Respect is normally earned. 

I hope you feel a bit more heard now. Again, sorry that we've given you a negative view of the committee. We're not perfect. 

If anyone on the committee feels I've offended them with this post, please contact me privately. I'd be more than happy to talk, at length, about it. I'm tired of keeping silent about this. This post may have messed up in a few places, and I'm sure we can work it out and maybe edit it if you can show me why and where. 

@avinassh - no, there is no age requirement, or contribution requirement. But you should want to do this job, which normally means you understand the community and what is involved. :)

**Comment by benjamingr** [comment]
@rachelnicole hey, we don't really know each other too well.

Would you mind explaining what your work at CommComm has involved so far?

I'm ashamed to say, but the only issue I've seen so far was [about the CoC](https://github.com/nodejs/community-committee/issues/111). This is _probably_ because in our local community we don't use twitter a lot (stack overflow chat and meetup mostly) so we miss a lot of the public facing activity members of CommComm have.

Things like NodeTogether look really cool! (I was not familiar) I'm looking specifically for what you've done in CommComm here. I realize I don't have a vote here - I'm just curious as a community member.

**Comment by rachelnicole** [comment]
@benjamingr just like everyone else on the Community Committee, I attend our meetings and participate in discussions that @nebrius had brought to attention for the agenda that week. I also was at the collaborators summit in Berlin. 

I don't know if you're wanting any tangential information outside of that, but I've spoken at every Node Interactive that's taken place about various projects (and a lot of other confs, but thats most relevant), prev two Node Summit's on panels about community and I'm deeply invested in bringing new people to Node (totally new programmers, and those from other langs) through interesting projects as an alternative to just talking about enterprise applications. 

Right now I'm a Technical Evangelist at Microsoft. Previous to that I was a Software Engineer at IBM Watson, and Adobe Behance. I switched from Engineering to Evangelism because I was doing so much with Node and communities in my spare time, that it seemed like the natural progression of things.

I hope that's helpful!

**Comment by benjamingr** [comment]
@rachelnicole that's very helpful, thank you for taking the time to explain.

**Comment by williamkapke** [comment]
@nebrius proposed some reasonable deadlines- but we've fallen behind on them. Oops!
- Nominations ended a few days ago.
- Elections were requested to start yesterday.

It looks like we have 2 nominations: @rachelnicole and @bnb

@hackygolucky Hopefully we can look to you to set up the voting ASAP? Not sure how long it would take you, but I suggest we keep voting open for a min of 4 days (the duration @nebrius requested). Let's be specific about the end date **and** time though.

As this was a resignation, the elected member will serve for the remainder of @nebrius's term.

**Comment by hackygolucky** [comment]
Question! do members voting want their vote to be transparent? We haven't technically had to have an election before and I wanted to see 
1. should members selection be visible? 
2. should the election be public vs. something else scoped to the members, such as the commcomm email list?

Once, i know this, I'll set up the vote with a close date and time 4 days after open.

**Comment by rachelnicole** [comment]
I'm fine with it being public.

**Comment by renrutnnej** [comment]
I'm fine with it being public as well, and was hoping it would be resolved by the end of this week :(

**Comment by bnb** [comment]
I'm fine with it being public as well. 

@hackygolucky For additional context, with regard to 2: do you mean the ability to vote or the ability to _see_ who voted? Pretty sure the latter, but want to make sure I understand the wording correctly 🤔

Given the concern @renrutnnej voiced, I'd be +1 for closing the vote on Friday or Monday.

**Comment by williamkapke** [comment]
I would like to set the precedent that all votes for elections use https://en.wikipedia.org/wiki/Secret_ballot.

**Comment by bnb** [comment]
@williamkapke Would love to hear specific reasoning behind that. I have no problem with it being open, but if there is a legitimate reason to use a secret ballot process in the CommComm and other Org groups I am +1.

If there are members who _do not_ feel comfortable voting publicly - or would be +1 for votes to be private - I believe we should respect their wish and have a private vote.

**Comment by MylesBorins** [comment]
If there are members who do not feel comfortable with a public vote and would like to anonymously voice that concern I would like to make myself available to proxy that. Personally I am +1 on transparency for this

**Comment by williamkapke** [comment]
@bnb There are several reasons in the wikipedia article I linked. More contextually, some TSC members in the past expressed their discomfort to doing it in the open for those same reasons.

Personally, if it isn't private, I am forced to abstain.

Moreover, why are folks here so interested in knowing each individual choice? This vocal desire to know exactly who your committee mates favored is already feeling threatening.

**Comment by gr2m** [comment]
I’m okay with making my vote public, too

**Comment by rachelnicole** [comment]
@williamkapke For me I think either of us would be fine as chair of the committee so I'm not going to take it personally if someone doesn't vote for me? I don't see how it's threatening at all?

**Comment by renrutnnej** [comment]
@williamkapke I'm not comfortable with your assumption of why I'm okay with my vote being public. 

I don't care who other people vote for, in the same way that I don't care who knows how I voted.

I do care about moving the process along, and resolving the issue. 

I don't understand where any of this thread is vaguely threatening in the slightest.

**Comment by refack** [comment]
I'm with @williamkapke. While a public vote seems like a more "brave/honest" path, the process of choosing such a process has selection bias. People who don't feel comfortable with voting in a public manner, will likely abstain from voicing their opinion on the openness of the process. In this case IMHO the process should err on the side of caution vs openness.

Plus there is already one member who stated they'll abstain from a public vote:
![image](https://user-images.githubusercontent.com/96947/30396459-b13fe182-9897-11e7-8e26-417eee9653a4.png)

**Comment by hackygolucky** [comment]
Okey dokey. I think it's a good point to remember that when folks are sharing their opinions here, they are _just_ that. The individual's opinion. It is one vote(if you are a CommComm member). Yours can be different, and votes are a regular part of process when consensus doesn't occur(and that's common with our work!). We can ask questions to understand their argument. We should not make assumptions. Feelings are valid, even if you do not share them. Please be respectful of that.

So, we have objections to the idea of election voting in public. We can vote on this, if y'all would like, and move forward from there. 

Otherwise, my revised recommendation as a compromise: I'm a fan of transparency, but **we can have transparency in vote count without exposing an individual's selection for Chair. The venue for vote, regardless, I don't think needs to happen publicly. The process and result, however, should be published.** Does this sound good?

**Comment by rachelnicole** [comment]
@hackygolucky I'd rather not vote on how we vote so I'm fine with that.

**Comment by bnb** [comment]
@hackygolucky +1.

**Comment by renrutnnej** [comment]
@hackygolucky +1

**Comment by bnb** [comment]
Removing agenda tag and closing, as the election is closed and we've landed on our new co-chairs 😁
