### ISSUE TITLE
Explain inclusivity better

### ISSUE THREAD

**Issue by benjamingr** [nodejs/community-committee#117]
Hey,

Reading the recent Reddit complaint issue about a foundation member made me think Node.js doesn't do a particularly good job explaining _why_ Node.js does all the inclusivity work.

I think people reporting comments like:

> "never underestimate the wrath of a mildly inconvenienced white dude (and yes it is all dudes complaining)"

As CoC violations indicate that this committee needs to communicate better _why_ it is working towards a more inclusive community. That post has over 300 upvotes which indicates at least some people agree with it - I suspect this is mostly because Node.js isn't communicating clear information about its decision making process here.

I'd like to see CommComm communicate the reasons to well... the community:

 - Why a Code of Conduct is used, what it fixes and why it's something Node.js does.
 - Why giving people from disadvantaged groups equal opportunity is something Node.js tries to do, why it makes sense from both a project and personal PoV.
 - Why Node.js is working towards a more inclusive community, what steps are being done, and how they don't interfere with the development process but help it. 
 - That this works, hopefully with examples of people who are traditionally excluded from contributing to open source but have made significant contributions to Node.js. 
 - (We can also discuss people who have _tried_ to make contributions but didn't because of the atmosphere, I can name a few but I'd rather keep it positive).

I'd like to see the _why_ explained in a clear place people can read. To be clear, I am personally in favor of the CoC and the ongoing inclusivity efforts in Node.js and have been participating in monthly onboarding events in my local community as well as being a contact point for questions. I just think the project can explain this a lot better. 

What do you think?

**Comment by gr2m** [comment]
Hi Benjamin, thanks for caring ❤️ 

Just a heads up that the past week has been very draining for all members of the Community Committee. We’ll get back to you and everyone else wondering the same thing, but please be patient with us.

**Comment by benjamingr** [comment]
Hi @gr2m, thanks for the response. There is no rush here, this issue is not about me personally so don't feel any need to get back to _me_ about it (I'm pretty sure I understand why we're working towards a more inclusive community personally). 

I opened this issue more for tracking communicating the rationale behind all that to the broader Node.js community.

I believe that the fact a portion of our community is in "that reddit crowd" is a reason to talk to them _more_ rather than ignore them or label them as trolls. There is a Node.js community there that we're marginalizing because some trolling has come from there. 

The way it looks like from _their_ side we're not giving them an easy way to have a meaningful dialog about all that happened. Worse, we're not explaining why the Node.js organization is behaving the way it is. 

I think we owe these community members answers. Here's the fun part: I think we actually have _good_ answers and compelling reasons for the CoC and the project's behavior. We're just not communicating them anywhere :) (or at least, I could not find it, the closest was the VALUES.md doc in ayo and that's still pretty far from what I'm talking about here)

**Comment by Marak** [comment]
You said, `I believe that the fact a portion of our community is in "that reddit crowd"`

It's actually the majority of Node.js users. The CommComm caters to a vocal minority of social justice seekers. The vast majority of Node users are remaining silent on the issue of inclusivity. They either don't care enough to comment, or are afraid at the social backlash of questioning these *mob rallying* Twitter users that belong to this group and purport to have Node's best interests in mind.

**Comment by benjamingr** [comment]
@Marak thanks for discussing. I'll reply here but I want to clarify I hold no official position and all my answers are purely my own views.

> The CommComm caters to a vocal minority of social justice seekers. 

I am not involved in CommComm so I can't really comment on that - but that is not the impression I have.

I'm a fan of social justice (is that a derogatory thing in US culture?) but not really in the context of Node.js itself. I think that if you look at the collaborator list it's very diverse and part of that diversity is because Node.js has done a lot of work to be inclusive.

To say it out loud - people who would not ""traditionally"" be participating in open source are writing a significant amount of the code and tooling in Node.js.

> The vast majority of Node users are remaining silent on the issue of inclusivity. 

I think that a vast majority of potential contributors (not sure about end users) would prefer contributing in a safe environment where their religion/race should not impact their ability to contribute. I'm not sure if we have data to back that up (I'm not in CommComm).

> are afraid at the social backlash of questioning these mob rallying Twitter users that belong to this group

I sure hope that's not the case either. If from where you're seeing this this looks like a "mob war" it means things aren't really going well.

I think Node.js needs to communicate with those users (regardless of what percentage they are, and even if they're not a majority) and hear them out. Currently we don't have anywhere that explains why Node.js has a code of conduct, what it helps solve and so on.

Disclosure: I'm not on Twitter, so I can't really judge what's going on there.

**Comment by rachelnicole** [comment]
![dixs-o4uiae8q3j](https://user-images.githubusercontent.com/228230/29832173-57229e26-8cb5-11e7-86f6-fd9ddb92dd6c.jpg)

I'd like to point out that @marak called me a cunt today when I told him i didn't know who he was or care what he did because what we're doing now is important. It seems like he's just here to antagonize, and doesn't have anything constructive to bring to the conversation.

As someone who admittedly was 'gone for 5 years' I don't think he really knows what the majority of users want.

**Comment by HorizonShadow** [comment]
That's an ad hominem and isn't relevant to the topic.

**Comment by rachelnicole** [comment]
I think it's relevant to define here what is "the community" then. Because I work regularly with both corporate devs and new devs on a regular basis, who absolutely do **not** share the sentiment of those on reddit. 

Is it the people who are actually participating in org decisions, is it the people trying to contribute to core, is it those attending conferences? Is it select communities we oversee?

**Comment by Marak** [comment]
"the community" is every single person on the internet who uses Node.js or the JavaScript toolings built with Node.js. 

"the community" is not the exclusive group of people you meet with face to face at corporate events or conferences. This is a privileged position which is out of touch with the majority of the community.

"the community" is definitely not those who have pushed their way into governance positions as a way to pad their resumes or promote their own personal agendas.

**Comment by bnb** [comment]
One further point I'd like to add here: The Community Committee is tasked with building a more inclusive environment in the Node.js community, and we've been focused on that for the past few weeks.

That said, building a more inclusive environment isn't the _only_ purpose of the Community Committee. There are a suite of efforts that are generally meant to enable the Node.js Community - most of which (I can't think of one that doesn't) _also_ benefit inclusivity, because underrepresented groups are always going to be a part of the community.

The Community Committee is here to serve the Node.js community - _every single member_ of said community, by working to improve the community on many fronts.

**Comment by Marak** [comment]
If you want to make Node.js more inclusive, you need to remove these hateful people from any position of governance or influence.

If the first conflict resolution tool of a CommComm member is to take screenshots of the incident and post it to their personal Twitter looking for social validation, you are encouraging exclusivity and hatred. I've witnessed members of the CommComm looking to actively start conflicts and rally others to exclude people from the community.

If you have members of the CommComm making public statements including hatred towards gender, political, social, or religious beliefs, you are not encouraging inclusivity.

**Comment by Fishrock123** [comment]
Fwiw, there are some good bits on inclusivity in one of Isaac's recent posts: https://github.com/nodejs/node/issues/15011#issuecomment-325402892

**Comment by benjamingr** [comment]
@Marak if you are here in order to have a constructive discussion about Node.js can communicate better that's great - but I'm not sure what you hope to accomplish by the third paragraph of the last message. 

---  

@rachelnicole has there been any prior work in identifying big user groups in online community? I can only speak of my local community but in my local community:

 - There are 3 big Facebook groups, 1 specifically for Node.js and both me and @refack are present there.
 - There is some reddit activity but not much. 
 - There is some Twitter activity. I even opened an io.js locale account so people can ask that questions in the local language. It is small though.
 - There are several meet ups - the larger one (which Myles spoke in) meets about once a month with ~200 people.
 - There are conferences - but only about 4 a year that are "big".

There are about 10 times as many people in the groups than in the meetups, and about 10 times silent people who are members that don't participate.

I'm not sure if Node ever mapped it out. I gave a talk about Fetch yesterday and was asked about the Ayo fork (to which I replied Node.js users should not be concerned at all about the project at this stage).

We also meet about once a month and onboard contributors - that's about 20 people. Anecdotally the group that meets to code is a lot more diverse than the larger group but I don't think that's anything on my part but just the local community.

**Comment by hackygolucky** [comment]
@Marak A recommendation on persuasive arguments– it is not helpful to start your case by making statements, not backed by data, on who and where the Node.js community lives. While you have existed in some way or another for many, many years in the Node.js community, you also are making lots of stated assumptions in repos and on Twitter about folks you are engaging with. I would ask you to refrain from doing so further. You can make a helpful argument without coloring it with the added opinions that make people want to dismiss your message with the messenger.

And I'll ask that from **everyone else participating in this thread as well**. 

The Node.js community is comprised of many subsets of communities and is anyone who is or wants to write Node.js and are trying to participate. There's potential there. There are lots of folks who are at different levels of engagement with the core project. There are folks in the ecosystem. There are spaces that the project and the foundation can help control in terms of the Code of Conduct and safety being applied. There are spaces we cannot. We can hope that there are stewards of the general community values who will help make _those_ other spaces better. We can help do that when we participate there. We also absolutely work to ensure the spaces we do have control of how folks engage with one another are healthy. This is clearly not feeling very much like that right now.

@Fishrock123 Thanks Jeremiah! That's a good post.

**Inclusivity**, in this context, is an intention or policy of including people who might otherwise be excluded or marginalized to create a productive work climate of trust and respect. It builds a healthy project. More, varied perspectives produces better outcomes. We are working hard. We want to enjoy our time and be productive. Communication is paramount for that. We have big barriers to that as humans with very different life experiences, cultures, and spoken languages.

**Why do we value this?**
It’s about creating opportunities for everyone.
Diversity and inclusion bring us all opportunities to learn from others and grow. We all become better with more diverse views around when we are able to listen and learn. 
It’s good for the health of the project–diversity of thought improves project outcomes.
We’ll get left behind. Other organizations are doing a good job with this, and we shouldn’t lose contributors to our project only because they don’t feel welcome. That’s the silliest.

We ask of total strangers to collaborate on a project that we all benefit from.  In order for them to feel welcomed and stick around, they should feel like they belong. 

To create that sense of welcome, barriers to access and biases must be surfaced. People must feel safe enough to contribute. An inclusive, open-source community will result in better code from a more diverse range of developers. We are making up for a lot of lost time due to systemic failures and biases.

**Comment by bnb** [comment]
@Marak if you have an issue with someone from the CommComm - or the Node.js org in general - actively encouraging exclusivity and hatred, I *urge* you to report it to report@nodejs.org. We do take accusations like this very seriously, and will go through the full moderation process for *every* report. 

This issue is not the forum for this kind of report, nor a platform for discussion around it. You're straying from the intended topic of discussion in this issue (explaining inclusivity in Node.js better) and taking it down a path of discussing (one or more?) Community Committee members' actions.

If there's a discussion to be had around that, please feel free to open another issue. Again, if you feel any individuals actions need to be examined by the Community Committee or the Node.js moderation team/repo, I **urge** you to use that proper mechanisms to report that.

**Comment by benjamingr** [comment]
@hackygolucky that's a really good start.

I was hoping we could solidify these things into a document which we can refer people to. 

Do we have any statistics about members who are not from a "classic" collaborator pool that we're proud in? I can name anecdotal examples but I was thinking something like:

 - Why does Node.js have a Code of Conduct?
 - What's inclusivity? What does it mean?
 - Why does it make technological sense for Node.js to have a CoC and care about inclusivity.
 - Some stories of people who are not from a "traditional" contributor background and have made significant technical contributions to Node.js (hopefully without singling out people)
 - Some stories of places Node.js has not handled itself well in the past with new collaborators.

I think explaining the CoC in terms of "this means more collaborators, more code and better technical features in the long run" would go a lot better than explaining that it is the right/just thing to do.

I think that we should communicate that this is the rational choice technically and we choose it because it is the responsible thing to do from a technical standpoint. I truly believe that, and I also believe it is the right thing to do as people in general - but I don't think that would carry as much weight with the general community.

**Comment by rachelnicole** [comment]
@benjamingr these are all really really great. I know @ashleygwilliams will definitely have a lot of input on some of your points with her experiences teaching groups all over the world w/ Node Together too.

**Comment by bnb** [comment]
>Do we have any statistics about members who are not from a "classic" collaborator pool that we're proud in?

@benjamingr To this point, there may be some info we can use from the Node.js User Survey (here's the "[executive summary](https://nodejs.org/static/documents/casestudies/Nodejs_2017_User_Survey_Exec_Summary.pdf)" -
 we may need to go deeper) the foundation put out a while ago - @hackygolucky will probably have some more details, but there's quite a bit of good info there.

**Comment by hackygolucky** [comment]
I can dig in if you need, but the Executive Summary should have those numbers. If not, the Education summary does.

**Comment by DelanoJ84** [comment]
> I think people reporting comments like:
> 
>     "never underestimate the wrath of a mildly inconvenienced white dude (and yes it is all dudes complaining)"
> 
> As CoC violations indicate that this committee needs to communicate better why it is working towards a more inclusive community. That post has over 300 upvotes which indicates at least some people agree with it - I suspect this is mostly because Node.js isn't communicating clear information about its decision making process here.

Is this referring to only that 1 quote from the 10+ on the list or does it also include the sterilization, gendercide, and targeted harassment ones?

**Comment by ljharb** [comment]
It's referring to people *reporting* all those comments.

**Comment by DelanoJ84** [comment]
So is the problem that the board only found out about these sterilization and gendercide comments after third parties reported it?

**Comment by rachelnicole** [comment]
@benjamingr could you please remove the link to the reddit post & direct reference to @ashleywilliams as we can discuss how to better explain inclusivity without drawing any more attention to it.

@DelanoJ84 could you also please put your comments into details blocks as it's off topic, and unrelated to discussing how to better explain inclusivity.

Discussions of active CoC reports is not on topic, if you'd like to report something plz email report@nodejs.org

**Comment by Trott** [comment]
It seems like perhaps this should be closed. Feel free to re-open (or leave a comment requesting that it be re-opened) if you disagree. I'm just tidying up and not acting on a super-strong opinion or anything like that.

**Comment by benjamingr** [comment]
I don't think that this issue has been resolved @Trott - the document about it hasn't been written yet. Anyone from @nodejs/community-committee wanna try and pick it up?

**Comment by rachelnicole** [comment]
@benjamingr do you have an example of another open source community that has a document along the lines of what it is you're looking for? We had a lot of discussion earlier on in the thread, but I don't quite understand the need for additional justification to why we need a CoC / why we do inclusivity work. 

Would the work we're going to be doing in https://github.com/nodejs/community-committee/issues/156 justify this? If so I'd like to agree with @Trott and move to close this.

**Comment by benjamingr** [comment]
@rachelnicole I'm not familiar with other projects dealing with these issues like Node.js does, but I'm definitely still in favor of having a document explaining:

 - Why a Code of Conduct is used, what it fixes and why it's something Node.js does.
 - Why giving people from disadvantaged groups equal opportunity is something Node.js tries to do, why it makes sense from both a project and personal PoV.
 - Why Node.js is working towards a more inclusive community, what steps are being done, and how they don't interfere with the development process but help it.
 - That this works, hopefully with examples of people who are traditionally excluded from contributing to open source but have made significant contributions to Node.js.
(We can also discuss people who have tried to make contributions but didn't because of the atmosphere, I can name a few but I'd rather keep it positive).

The CommComm can of course decide not to write such a document or not do so in this format. I just think there is a lot of value in explaining these things to people in a clear way. 

I am not a CommComm member, as a project member my recommendation is to add this issue to the next meeting agenda and either decide what are the next steps in explaining these things are(by someone from CommComm stepping up to write it for example) or decide that we shouldn't have such a document. I acknowledge that this is not a shot I make though :)

Thanks.

**Comment by bnb** [comment]
@benjamingr hey there - going to add the cc-agenda label to this so we can discuss it in tomorrow's meeting (and, if attendance is low because of the holiday, discuss it in the meeting after that). Don't want you to think that we don't care about this, I think it's just slipped off of our radar a bit. Hopefully we'll be able to get you some more context soon!

**Comment by jakeNiemiec** [comment]
There is something unsettling I heard in the CommComm livestream today that is related to this issue:

>olivia: ["This might be awful to say but the issue is kind of, a little bit, confused...like the people, the author's a little bit confused about what _can_ do \*laughs\*"](https://youtu.be/hJZzgGZBCXo?t=28m47s) (this is about `NodeJS Africa Comm-Comm` #237 )

You don't laugh at someone who looks to your organization for inclusion/support. Especially when they did exactly what your `README` says to do:

>[`README`](https://github.com/nodejs/community-committee/blame/master/README.md#L12)"The Community Committee is tasked with further building out the Node.js Community...we're looking for help. **If you have your own ideas on how we could engage and build the community, feel free to create your own issue!**"

Understandably, the livestream response was: "**need to respect our members time**". Olivia's official response:

>...unfortunately the Community Committee doesn't currently have the resources to actively support this effort in an official capacity, but you're very welcome to ask us for help in case you have any questions!

**Comment by jakeNiemiec** [comment]
There is something unsettling I heard in the CommComm livestream today that is related to this issue:

>olivia: ["This might be awful to say but the issue is kind of, a little bit, confused...like the people, the author's a little bit confused about what _can_ do **\*laughs\***"](https://youtu.be/hJZzgGZBCXo?t=28m47s) (this was about `NodeJS Africa Comm-Comm` #237 )

You **don't** laugh at someone who looks to your organization for inclusion/support. Especially when they did exactly what your `README` says to do:

>[`README`](https://github.com/nodejs/community-committee/blame/master/README.md#L12)"The Community Committee is tasked with further building out the Node.js Community...we're looking for help. **If you have your own ideas on how we could engage and build the community, feel free to create your own issue!**"

Understandably, the livestream response was: "**we need to respect our members time**". 

I feel that the response does not reflect the values that those specific people champion in issues like #224 :
![meta__target_number_of_members_and_expectations__ _issue__224_ _nodejs_community-committee](https://user-images.githubusercontent.com/16782063/36003455-c8f9d802-0cf3-11e8-9941-245e71d11aed.jpg)

This is a great opportunity to put these words into action. I would love to see @codeekage admitted as an observer in #235.

>"I am 100% ready to contribute into making it [Node.js] a success in Africa".

Two Node.js enthusiasts reach out to CommComm in order to \`_build out the Node.js Community_` in Africa (aligns with CC's [responsibilities](https://github.com/nodejs/community-committee/blob/master/GOVERNANCE.md#section-5-responsibilities-of-the-cc) and Olivia's diversity goals)...

I think they deserve a bit more than 3-year-old links and stickers.

**Comment by oe** [comment]
@jakeNiemiec Ah, sorry about that. What I meant by "confused" was that I personally wasn't sure if @codeekage wanted to establish a presence for Node.js in Africa, participate in CommComm efforts, or both. It was wrong of me to assume the latter, especially given their request to participate as an observer (which there are two of that all of us somehow seem to have missed?). Apologies for the poor wording and decision-making on my part.

**Comment by rachelnicole** [comment]
@jakeNiemiec I don't think Olivia's was laughing at the people wanting to participate, it sounded like to me more out of frustration.  I think it's more of a situation where as members of the CommComm we're confused as to how to deal with a situation where there's a misconception of our reach, and level of support. 

As in we don't run conferences, and we don't run node schools. We're here to assist with information and support. Primarily to support the community on the level of bringing them in to support Node.js working groups and initiatives directly under the foundation. 

I absolutely think that we can help them get pointed in the right direction to get what they want to get done accomplished, but there need to be more conversations about expectations and needs.

**Comment by rachelnicole** [comment]
@jakeNiemiec also if you believe we should support individuals efforts more, might I recommend joining the [Evangelism Working Group](https://github.com/nodejs/evangelism)? It could always use more people who are passionate about Education & Inclusivity outreach. The more people we have helping out, the more support we can give. :)

**Comment by codeekage** [comment]
@jakeNiemiec thank you for your concern. But I totally understand if they are confused, it can be really difficult to paint a picture from few words and not a detailed explanation. 

That's why I'm suggesting the Comm-Comm should have a support or a representative that takes time to have full detailed discussions with authors having complicated issues like mine. This will help in terms of clarity and also diversity in the community. 

I strongly understand that community does not run conferences or node school, but I believe that the community supports underrepresent groups, communities probably individuals spread NodeJS around the world. That's the support I believe I should equally get. 

I am more than happy to work with the community to see NodeJS Foundation grow in Africa. I'm open to a formal conversation or probably informal discussions on how NodeJS Foundation and Comm-Comm will be of help to the group of people I will be representing probably as an ambassador.

@oe thank you for discussing and being a spokesperson.
thank you @rachelnicole  for clarity on what NodeJS Foundation is more committed to.

**Comment by jakeNiemiec** [comment]
@oe 
>It was wrong of me to assume the former, especially **given their request to participate as an observer** (which there are two of that all of us somehow seem to have missed?).

I should have considered that this just went under the radar. I probably wouldn't have commented here otherwise, sorry for putting you on the spot.

@codeekage
>@jakeNiemiec thank you for your concern. But I totally understand if they are confused, it can be really difficult to paint a picture from few words and not a detailed explanation.

I think the situation is better understood now for everyone. I only posted here because I thought there was exclusion happening, when in reality, everyone here is a volunteer and people get busy.

@rachelnicole 
>@jakeNiemiec I don't think Olivia's was laughing at the people wanting to participate

I didn't think she was, I have edited my post to reflect the new information. 

>if you believe we should support individuals efforts more, might I recommend joining the Evangelism Working Group?

I'll check it out, thanks.

**Comment by benjamingr** [comment]
Hey, the discussion here is interesting - but I'm not sure where the original issue currently stands. 

Any update on what you decided (if you had a chance to discuss it already) on writing a document?

**Comment by mhdawson** [comment]
This was discussed in the last CC meeting, Olivia volunteered to spends some time on it.

**Comment by benjamingr** [comment]
Thanks, appreciated

**Comment by de-tester** [comment]
Since that's the only place that referencing closed [#324](https://github.com/nodejs/TSC/issues/324) i have no choice but ask it here. 

Are there any updates on that issue? Was that CoC complaint reviewed as stated? Are there any notes on the meeting or review if it took place?

**Comment by benjamingr** [comment]
Hey, let's please keep this issue on-topic about how Node.js can explain inclusivity better. Discussing individual members is entirely inappropriate anyway (I was wrong to do it here initially, acknowledge my mistake and I apologize).

Not sure discussion can be kept on-topic anymore - so I'm also OK with closing/locking.

**Comment by oe** [comment]
Closing since this issue has been led off-topic two times and I don't believe there's anymore discussion to be had here until a draft is proposed.
