### ISSUE TITLE
Promoting collaborators to website WG members?

### ISSUE THREAD

**Issue by fhemberger** [nodejs/community-committee#121]
(Hi, not sure if this is the right place for this issue, if there's a better fit, please let me know.)

Currently, there are four people listed as Website Working Group Members:

- Phillip Johnsen (phillipj)
- Mikeal Rogers (mikeal)
- Rod Vagg (rvagg)
- and me.

With Mikeal's departure and Rod's role in the community currently being discussed, this leaves only Phillip (who's currently busy with work and doesn't seem to have much time) and me. The [project governance document](https://github.com/nodejs/nodejs.org/blob/master/GOVERNANCE.md) states:

> There is no fixed size of the WG. However, the expected target is between 6 and 12, to ensure adequate coverage of important areas of expertise, balanced with the ability to make decisions efficiently.

There has never been a process for onboarding new members to the WG, at least it hasn't been done since the WG exists. A few members left on their own after being asked if they still want to be on the WG after a longer time of inactivity. (So there was no official "vote", just an informal "Hey, haven't seen you around in a while, are you still interested in the WG?")

So I think it would be nice to add a few collaborators to the WG, but I don't want to decide on the process alone. How do other WGs handle this?

**Comment by TimothyGu** [comment]
Slightly off-topic, but I would be interested in helping out with the Website WG.

**Comment by bnb** [comment]
Generally these guidelines are defined in GOVERNANCE.md for a WG - you can take a look the ones for the [Evangelism WG](https://github.com/nodejs/evangelism/blob/master/GOVERNANCE.md#collaborators) to see an example. 

Generally this is a loose process, and varies in intensity and execution from WG to WG. For example, the Security WG has a more strict membership process and is currently undergoing some discussions around tightening it even further. On the other hand, if someone were to become active and consistently contribute in the Evangelism WG I have little doubt they'd be added as a member because *any* contribution is very significant and impactful there.

I have discussed with several peers and friends in the past who have expressed an interest in contributing - I'll point them to this issue. Additionally, it *never* hurts to share on social - there are often people looking to get started with contributing, and the Website WG is an **amazing** place for this.

**Comment by bnb** [comment]
One thing that would help: Have a place to land for new members/those interested in working on a website redesign. Even creating an issue to ask for interest in contributing would be a MASSIVE help - I know that'd be a great piece to share and help drive new contributors. ❤️

**Comment by gibfahn** [comment]
I'd also be interested in helping out with the website WG.

**Comment by XadillaX** [comment]
I'd also be interested too.

**Comment by fhemberger** [comment]
Just as a side node, there's no big difference between a collaborator and a WG member in the website WG. The only differences are:

- We're compiling a list of GitHub committers from time to time to have them added as collaborators
- When a change is debated and no consensus can be reached, the WG members decide together (which was rarely needed so far)

**Comment by MylesBorins** [comment]
I'd like to advocate for making all committees wg members. I'm not sure the
hierchy is needed

**Comment by fhemberger** [comment]
@MylesBorins I'm totally fine with that as well.

@bnb I don't think we have a lack of people willing to help implementing the design. It's just the design itself (or to take a step back – the general content/ux direction) we've been waiting for. There were comments in the past that "the foundation is working on something" (probably involving the people responsible for the overall Node.js corporate design and/or Leo). But I haven't heard anything back for probably a year now. ¯\\___(ツ)___/¯

**Comment by fhemberger** [comment]
Suggesting to join both groups for the website WG, closing.
