### ISSUE TITLE
If someone submits a PR, should we invite them as an Observer?

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#143]
After the last week at Node Interactive, we've discussed a lot around enabling people further. 

One thing I'd like to discuss is if there's a first time contributor to the repo, should we automatically invite them to meetings as an observer? Of course there is no requirement to come, but I think it's a good first step to encourage further contributions.

**Comment by gr2m** [comment]
I like the idea, I’d like to try that out

**Comment by refack** [comment]
IMHO reaching out with a personal message to the author, welcoming them, thanking for the contrib, and asking them if they would like to join, might have a higher impact.

**Comment by refack** [comment]
P.S. This something we are trying out in "core". Also striving to assign a "champion" to each PR, so that the author has a human contact, and someone who is explicitly on their side.
RE: https://github.com/nodejs/node/pull/16016 If it wasn't part of C&L I'd also add a few words about the process (the possible review back-and-forth and 48 hour minimal timeframe).

**Comment by bnb** [comment]
General consensus was "no" on this, pending some other efforts around Observership. Going to close it for now.
