### ISSUE TITLE
Prototype self-hosted IRC server

### ISSUE THREAD

**Issue by nebrius** [nodejs/community-committee#19]
After [discussion](https://github.com/nodejs/community-committee/issues/11), there is interest in exploring a self-hosted IRC server setup. Self-hosting allows us to implement monitoring, logging, and authentication models that enable the kind of IRC community we want to grow.

The first step is to create a small-scale prototype to get a closer understanding of the effort and logistics involved in a self-hosted IRC server with these qualities. This prototype does not need to be scaleable or production-grade, but it should showcase the features we want.

Here is a non-exhaustive list of the features I think we should have (feedback requested):

- Authentication and login using GitHub to simplify the login experience
- A web client that user's automatically get logged in to, along with a way of making this optional for folks that want to use a different client
- Logging/auditing of all messages, along with time-limited storage of logs/audits.

**Comment by ashleygwilliams** [comment]
there is not consensus on this.

**Comment by hackygolucky** [comment]
@nebrius Because I am not aware of costs, if any, can you also get an idea of what would be required for infrastructure costs on this? 

I'd like for us to be working concurrently on the logistics of various parties voting on this as well(opening another issue) so we don't have too many blockers on getting folks to decide the Final Form of this.

**Comment by nebrius** [comment]
> there is not consensus on this.

Sorry, I jumped the gun on that a bit, OP edited.

**Comment by homosaur** [comment]
Have y'all looked into RocketChat yet? Essentially OSS Slack. I'm using it with some orgs that need archiving for Slack but are cost sensitive. It's actually pretty good.

**Comment by homosaur** [comment]
And just for very rough cost estimates I'm on a 3500 member RC instance that's running on a T2.large AWS server. Plenty of growth room, approx $68/mo

**Comment by hackygolucky** [comment]
@homosaur I think it was discussed quite a bit in #11 but I also talked to other foundations using it when I was at the Open Source Leadership Summit a few weeks ago. It's still very early and the mobile support isn't quite there yet. There were also heavy concerns(as other mediums had) about accessibility. We're trying to focus on mediums right now that the community already exists in instead of whole-hog moving to a new tool.

**Comment by homosaur** [comment]
@hackygolucky I don't see any discussion of that RC specifically on #11 but can agree from personal experience the mobile app is not the best.

**Comment by nebrius** [comment]
The discussions in the other issues related to this one seem to indicate most folks don't want a centralized communication medium. As such, I don't think this issue is really relevant anymore, so I'm going to close.
