### ISSUE TITLE
Meetings schedule

### ISSUE THREAD

**Issue by Bamieh** [nodejs/community-committee#197]
I am not sure where the discussion happened, but i believe it was agreed to do the commcomm meetings every two weeks instead of every week.

It would be awesome if someone has the time to update the recurring event on google calendar to accommodate for this change.

**Comment by dshaw** [comment]
@Bamieh I think the Node.js Calendar has been updated to reflect the meeting schedule. I recommend subscribing to http://nodejs.org/calendar . The calendar currently shows Thursday, 2018-01-04 as the next scheduled meeting.

**Comment by dshaw** [comment]
@bnb @rachelnicole I'd love your confirmation that the CommComm calendar has settled at least for January and that the Node.js Calendar is up-to-date. As the `Champion` for @nodejs/user-feedback I need to schedule time to attend CommComm meetings and have a number of agenda items that need to be addressed. Thank you. 🙏 A little bit of clarity now will make the holiday break less stressful since the 4th occurs vacation time.

**Comment by Bamieh** [comment]
@dshaw Oops my bad. I have already subscribed to the calendar but it was still showing today's meeting for some reason 😄 . Seems that i have the meeting copied to my calendar and it doesnt reflect updates on the original. Feel free to close the issue.

Cheers!

**Comment by dshaw** [comment]
@Bamieh Yeah, I had the same thing happen to me with the previous CommComm meeting. I had copied it to my calendar.

**Comment by bnb** [comment]
@dshaw the next meeting should be this Thursday - I assume the meetings were entered manually and not as a recurring meeting, because I moved the last one and none of the upcoming meetings were updated - noted, and I'll set them up as recurring for the future.

@Bamieh as per our schedule, there should normally be a meeting every other week - hopefully the calendar wasn't too confusing, an oversight on my part. Since the last meeting was December 14th, the next meeting should be December 18th - I'll be creating the issue tomorrow 👍

**Comment by Bamieh** [comment]
@bnb It is clear, it's just that i have copied the old calendar so i got confused, my bad.

> Since the last meeting was December 14th, the next meeting should be December 18th 

28th*
