### ISSUE TITLE
governance: who has voting rights?

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/community-committee#21]
It's not clear to me who has voting rights on the CC (e.g. for purposes of bringing on a new member) - is it all members or only advisors?

**Comment by nebrius** [comment]
> Is it all members or only advisors?

According to my read, it's members according to GOVERNANCE.md (note: I don't think that advisors are a proper subset of members).

**Comment by Fishrock123** [comment]
> Adviser: a Collaborator within a Community Project elected to represent the Community Project on the CC.

They... are? I'm not sure, but maybe the doc is missing distinctions, or confusing the two terms?

**Comment by Fishrock123** [comment]
Or does this mean they are just a member but from an outside project with a fancy title?

Why bother making the distinction considering how the governance works?

**Comment by nebrius** [comment]
> They... are? I'm not sure, but maybe the doc is missing distinctions, or confusing the two terms?

Oh, I think you're right, I missed that.

> Or does this mean they are just a member but from an outside project with a fancy title?
> Why bother making the distinction considering how the governance works?

It would _seem_ that way. I'm not sure we really _need_ a difference, although I think it also would be good for people to be able to officially represent their projects somehow

**Comment by williamkapke** [comment]
After re-reading the charter to verify, it looks like voting rights belong to anyone that is a Member of the Community Committee-- no matter their reason for being there. This makes sense to me. Ideally, the voting members should be people that are overseeing a wide range of CommComm matters. Advisors may not want to be that involved.

If we don't have a real need to define an `Advisor`, we should just remove that definition. Otherwise, maybe update it to:
```
Adviser: a Community Project member representing their project in an official capacity.
```
The current definition assumes each Community Project will perform some kind of assignment/election to have one of their Members be a representative. I think inviting anyone (whether elected or other) from a Community Project to participate and attend meetings is a good first goal. Once we see traction and get feedback with outside perspectives- we can revise.

IOW, Advisors seem similar to Observers** but with more definition of their origin/background/role.

<sup>** "Observer" is not a defined term - just something found in the wild within the Org.</sup>

**Comment by nebrius** [comment]
@williamkapke thanks for the writeup, and +1 to removing the `Advisor` definition, at least for now. I'm thinking it'll be a lot easier to clarify how this should work once we get one or two folks representing other projects as regular members on CommComm and have some real world data points to point to.

Do we want to file a new issue to track reworking the charter and close this as resolved? Or do we want to co-opt this issue and leave it open and with `cc-agenda` to track the charter work? I'm on the fence.

**Comment by nebrius** [comment]
I'm removing `cc-agenda` as there's nothing to discuss in the next meeting about this.

**Comment by bnb** [comment]
I believe we've addressed this with the distinction around Members and Observers. If I'm wrong, feel free to re-open or to create a new issue to discuss further 😊
