### ISSUE TITLE
meta: target number of Members and expectations?

### ISSUE THREAD

**Issue by Tiriel** [nodejs/community-committee#224]
Hey everyone!

First off, I hope I'm not throwing something too controversial here, but I had some questions wandering the vast emptiness of my thoughts. If it's too much of a hot subject, don't hesitate to close this. Secondly, you'll note I'm asking these question before meeting the current expectations to become a full Member. To the point then.

Although the current Readme and the Governance guidelines mention a target for about a dozen advisors, it doesn't say a thing about members, and the observer role as been removed, creating some kind of hole. Observers can be added, their attendance tracked, but governance states there are no requirements to becoming a member. Also, it looks like the CC is growing in number at a steady pace, and there are now 16 full members already.

As I'm not a full member, though I'd like to be, I don't think I'm qualified to PR some changes to these texts to make them coherent or more precise. But is it scheduled somehow? Do we discuss it in tomorrow's meeting?
Also, I know we fight for openness, but in the case of a top level committee, wouldn't it be better to somewhat set a limit to the number of members, or at least put requirements? Maybe simply make the proposal of new members a privilege of current members?

As said, I know this may be controversial, but I feel it to be really important. This doesn't mean I want the CC to become some sort of elite, and there are plenty of solutions so that pretty much everyone who wants can be included in the workings of the CC, via WG, Initiatives, etc etc.

But to me, if there's to be a symmetry between the TSC and the CC, each one of equal importance in its area, we should address these questions. Especially if we have to talk again about things like the ownership rights on the org. From what I understand, the CC is supposed to be of equal importance and equal rights and privileges as the TSC, so I figured it would make sense.

Thanks for reading anyway!

**Comment by pup** [comment]
This is something we've been somewhat discussing in private recently (I'm going to bring it up because I was the one that initiated the discussion), too. Essentially, the Community Committee is much less diverse if you include its current observers in the statistic, which I think is important, since diversity is a huge formational part of this committee, as it was partly formed from the old Inclusivity Working Group. I think we'll be lose a lot of valuable viewpoints and opinions if we become less diverse. We clearly have to change something, since our current list of Observers is hardly diverse. That's not to say I don't value everyone's input and work, simply that I don't think we can achieve as much if we're mainly made up of, well, straight white men.

I suppose I'm trying to say that I don't think the current process of Observer -> Member is working very well, in terms of diversity. Also there's obviously the whole GitHub org ownership issue, which raises completely different and important security concerns about the current process.

It's definitely something I'd like to discuss more this year, and even if we have to make drastic choices, increasing diversity is never _easy_, only pretending to care about it is.

**Comment by Tiriel** [comment]
@pup I kind of see your point, but just to give my two cents on the matter:
* I don't quite think we should assume the whiteness or the straightness of everyone on the observer board
* Even if it were, I think excluding someone because they are not an inclusivity target is still excluding, hence not inclusivity. I think it'd be better to encourage people of diverse origins, genders, orientations, or whatever, to step up.

Now I know that's not what your point is about, I just wanted to make sure we are on the same page on this. Although you're perfectly right about speaking about inclusivity being easier than doing inclusivity, it's something I do care about very much and try to uphold. and that brings the next point

--------

I do think too that the current process does not work very well, because the CC keeps accepting pretty much everyone who asks for it. It's great for a start, but I don't think it'll be quite manageable for long, and the meeting will require inventing new means of participating soon if we keep at this rate (could be a side project or an initiative though :blush: just joking). And there's indeed the question of representation and diversity. We have the chance of having one of the most diverse communities online that I've seen so far, we should try to promote that.

I hope I'm not misinterpreting or anything. If I do, I'm really sorry, but please keep in mind this is not my primary language.

Cheers everyone!

**Comment by pup** [comment]
@Tiriel Absolutely agree with your remarks, I was just basing it off the subset whose identities I personally knew. Also I suppose my main point was the gender ratio, so it may have been a bad choice to use "straight white man" there. Sorry about that.

And yeah, we've been coming to the conclusion that reaching out to minorities is the first step we need to do in order to start with increasing diversity in our own committee.

**Comment by bnb** [comment]
So I'll try to give some context:

A _lot_ of what's in our governance and contributing documentation is old. To the best of my knowledge, the majority of it was created when the CommComm was an idea – and solidified when it was proposed. That was over a year ago, sometime in late 2016.

Since then, the CommComm has evolved quite a bit. We've gained members, begun to work on new initiatives, and come to understand the role the CommComm has a bit better.

Since I requested to join as an observer (I believe I was the first person to go through the observer process, though I don't fully remember), I've had many discussions with individuals about the joining process and how it can be refined. We've had a _lot_ on our plate to get things settled and enable the CommComm to be a functioning committee that enables projects like i18n, user feedback, and the website redesign under it. As far as I can tell, we've hit a point where that part of our work is stable and consistent.

Now, it's time to address some of the rough parts of our governance to help ensure long-term sustainability and natural growth of the Committee.

Certain parts that you mentioned in your OP - like having a target of 12 members - have a lot of bundled context that has new precedent. 12 members is one example - I _believe_ this was based on the target number of TSC members prior to the TSC and CTC re-merged in ~August last year.

**Diversity:**
As @pup brought up, we've discussed this a bit privately. I am concerned about what they raised as well, and want to figure out what we can do to further enable diversity in the CommComm. I know for a fact that there are quite a few community members whose interests align with what the stated goals of the CommComm are, yet we're currently attracting members who fall into only a few specific verticals of diversity.

I am very eager to help enable the CommComm to lower any current barriers that are limiting/restricting interest and accessibility to the Committee.

**PRs:**
>As I'm not a full member, though I'd like to be, I don't think I'm qualified to PR some changes to these texts to make them coherent or more precise.

I'd definitely like to address this, and we probably should make a PR to the README: _Please don't hesitate to make changes and PR them._ If your PR is closed, it gives us a solid base to use in the future when issues are inevitably addressed. If your PR isn't closed, then it'll be merged! 😁

I hope that the perception isn't that you need to be a CommComm member to submit PRs, but definitely want to hear from the Observers to see if it is. If it is, that's a _failure on the CommComm's end_ that we need to fix.

**Membership requirements:**
The current membership requirement is 3 months of attendance [[ref](https://github.com/nodejs/community-committee/blob/master/GOVERNANCE.md#section-4-establishment-of-the-community-committee)]. That's one of the things I'd like to change most, since meeting attendance != engagement or activity. That said, we don't have an easy criteria like code commits so defining what criteria would be without being exclusive is the difficult part.

**Comment by Tiriel** [comment]
@pup 
> Also I suppose my main point was the gender ratio, so it may have been a bad choice to use "straight white man" there. Sorry about that.

No offense taken at all, I didn't took it personally as I don't relate entirely to this category. But I'm glad we are indeed on the same page, and I completely agree with you. I think we should then press on these matters. Community is of paramount importance for me and this one has real potential, I'd like to see the CC take the place it deserves in this community, and diversity is the one step we can't miss to achieve this goal.

@bnb 
> I hope that the perception isn't that you need to be a CommComm member to submit PRs, but definitely want to hear from the Observers to see if it is. If it is, that's a failure on the CommComm's end that we need to fix.

That's absolutely not the perception I had, no problem. It's more that I don't feel legitimate, because this particular text is of real importance and is some kind of "legal" text, so it seems weird to me that someone who is only half inside can ask to change it. But I guess you're right, any PR can be closed if it doesn't suit the needs at hand. I'll give it a try soon then.

Thanks you both for your return anyway, and I hope we can get more opinions on this. Unless you want the discussion to go back to private-land?

**Comment by bnb** [comment]
For context, this issue discussed and marked as related in today's CommComm meeting: https://github.com/nodejs/community-committee/issues/143

**Comment by Tiriel** [comment]
Thanks again for the context and for discussing this briefly today!

Is there a way we can discuss or even schedule a meeting to address all these issues re inclusivity qnd member picking/onboarding?
Some of these have been sitting here for quite some time and it seems I'm not the only one who thinks they are of great importance.

**Comment by bnb** [comment]
Going to close this since we've iterated a bit on the issues that were discussed in this issue nearly a year ago. If there are additional discussions to be had, creating new issues with modern/updated context would be ideal.
