### ISSUE TITLE
nodejs - members directory

### ISSUE THREAD

**Issue by WaleedAshraf** [nodejs/community-committee#227]
Not sure if there is already one, but I couldn't find one place to see a list of everyone who is a member of nodejs org OR a list of working groups members.

As I'm trying to get into the community, I keep seeing new contributors/members on different issues and I get curious like "Hy, this guy is an active contributor, I saw him in multiple WGs, how can I contact him? What other project he's working on? Where he's from?"

I know every WG has a member list on the main page but that's just GitHub username. And at some places, only name is written.

I think it'd be very helpful for the community if we make a public (read-only) google sheet with all WGs and give edit access to all members so that everyone can put their info. Give members option to put as much info as they want like: Name, Github username, twitter/fb username, email, location, company/Org, interests, what else he/she working on?

This would also be helpful for new members to know how they can reach someone from Nodejs WGs or nodejs org.

**Comment by bnb** [comment]
Generally you can tell by if someone has a label at the top of the bar, like so: 

![image](https://user-images.githubusercontent.com/502396/35416945-2c94839a-01f9-11e8-8494-52217bdfc67c.png)

There are a few variants of that mark, but the majority are related to being an org member.

There is a list of all current members of the Node.js GitHub org [here](https://github.com/orgs/nodejs/people), but only about half of the members show up there due to privacy settings.

In the context of reaching someone in a WG, members usually list their email address in the README.md or a document that lists the current members. The CommComm has this, as does the core Node.js repository.

Open to ideas, but we do need to be careful about sharing people's information and consent around usage of that information.

**Comment by Tiriel** [comment]
Although that seems like a pretty good idea, I don't know if it's really doable easily, at least like you proposed.

There like 600 org members, pretty much everyon in at least one or two WG/Teams, but some are active, some aren't, so drop out of a WG/team and enters anothers... Keeping such a document up to date would pretty much make enough work for a dedicated team.

And there are privacy issues like @bnb said.

**Comment by WaleedAshraf** [comment]
Agreed with the privacy issue, but I think it is covered when all the fields are optional for a member to fill or leave empty. On the other hand, some info of all open-source contributor is already on the web, which can be accessed by some Google/LinkedIn search. My point is to give the option to put it in one place/sheet.
For Example, I might be in Chicago in the first couple of weeks of Feb and I'm looking for someone from Nodejs community for a casual meetup. Similarly (If) I'm a member, I'd like to put my name on the list, so that if anyone comes to Pakistan and wants to meetup.
Maybe an unofficial sheet (members to maintain by them self) will work for this case. But maybe @Tiriel is right, too many members, too much to maintain.

**Comment by williamkapke** [comment]
Kind of related and maybe useful: I created a chart of WG members- but no longer keep it up-to-date. The data is built by a script that gets the names from the various READMEs.

http://node.red/decision-makers.html

Code: https://github.com/williamkapke/foundational/tree/data

**Comment by WaleedAshraf** [comment]
Nice chart.
I'll check If I can pull latest data using the scripts and update the summary.

**Comment by amiller-gh** [comment]
Doing some issue cleanup and would like to close this if we think its been resolved 🙂 
@WaleedAshraf, can we close this issue?

**Comment by WaleedAshraf** [comment]
A related issue to discuss further: https://github.com/nodejs/community-committee/issues/184
