### ISSUE TITLE
meta: accepting new observers

### ISSUE THREAD

**Issue by Tiriel** [nodejs/community-committee#231]
Hello people! Hope everyone's fine

It seems you'll have to endure yet another possibly controversial issue from me, sorry about that.
But, since we started discussing these sort of things in #224 , I figured I'd have to start this related issue.

Just quick context: we pretty much agreed that the current "observer to member" process won't work soon enough, and started discussing changing it. In the meantime, people keep requesting to be added as observers. More, if we keep to the current list of observers, there are nearly more of them than there are members (although obviously, some observers have not attended for some time).

Here's the thing:
* Is it technically possible according to our governance rules and the Foundation to impose a moratorium on new observer applications?
* If yes, what do you think of it? Wouldn't it be better to do that, maybe create a team/task force to work on the new process quickly, and then accept applications again?
* What do we do about the applications currently pending? (and of course, I include mine in that lot)

I'm not particularly fond of this solution, but I think it would be clearer, and it would allow for a time to deal with the current applications, decide if they are still evaluated on the old attendance criteria or on the future one.

**Comment by Tiriel** [comment]
And thanks @bnb for the discussion on the matter!

**Comment by tobyfarley** [comment]
I find this and #224 terribly off putting. I decided to join this committee because I felt this is where I could be the most useful and I was given the impression at Node Interactive that there was a need to rebuild this committee after the August Code of Conduct incident. What pressing crisis is driving this? I do not sense that there are too many people competing for too little work and I do not get the sense that there are too many people vying to speak, or take note etc. during committee meetings.

**Comment by Tiriel** [comment]
Firstly, sorry if I offend anyone. Please do bear in mind I'm just an Observer too, I do not speak for everyone but myself, and I do not have the slightest authority on each of these matters.
What I do try to do, is indeed participate in "rebuilding this committee". And I insist on "try". My participations might not be the most relevant ones, but everyone has their subjects and one's pressing matter is not its neighbor's.
Plus, please keep in mind that English is not my main language, so if some of my phrases seem offensive, don't hesitate to tell me, but don't think it was intentional.

> What pressing crisis is driving this? 

There is no "pressing crisis" in my opinion. I just feel that a good organization, a good infrastructure, is needed for every work to last and to be meaningful. That's the basis that seems essential to me. That's why I open a discussion (which is nothing more than a discussion).

> I do not sense that there are too many people competing for too little work and I do not get the sense that there are too many people vying to speak, or take note etc. during committee meetings.

I don't think that's the point, or at least that's not the problem to me. Much of the work we have to do can be done regardless of the status of the people doing it. We don't have to be Members or Observers of the ComCom to promote diversity. We don't have to be ComCom Members or Observers to convey our enterprise or our own feedback on Node.js.
The only need for Members on the ComCom is to take decisions and to champion the Initiatives/WG. All the rest of the work can be done inside the Teams/WG, and they do not require full Membership on the ComCom. One can work *with* the ComCom without being *in* the ComCom.

And the fact remains, if the ComCom keeps accepting new Observer and then Members, decisions will be harder to take, because consensus will potentially be harder to achieve. It may not yet be the case, because we are civilized folks and because no really controversial decisions have been made recently, but that does not mean it won't happen. Some discussions already take too much time in the meetings because many people want to have a say (and they should), and we had to report some issues to the next meeting already because we didn't have time for them. 
More people = more time on less subjects.

So yes indeed, there's work for everyone, but that does not mean to me that this work needs membership, and that the ComCom should continue to accept blindly everyone who asks for it. Technically, it's still a top level committe, one of two with the TSC, focusing on something largely as important as the tech: the community. I can't imagine the TSC with 30+ people arguing on technical matters. And I don't feel the community would be given the same importance if the ComCom had 30+ people arguing on its matters.

As usual, these are my two cents, and again, I don't want to offend anyone!

**Comment by hackygolucky** [comment]
@Tiriel @tobyfarley I think this is an important subject to bring up, as we want to make sure that what we're doing is serving the purpose(s) that we're here for: community and administrative work that helps support that for the Node.js project. 

My initial thoughts on this are that I don't think a pause on observers solves the problem that we need to address. If we worry about consensus building, we should examine the processes we have for how and when votes come to pass. I haven't seen us blocked on things in perpetuity that would warrant this being something occurring(though please feel free to offer examples that I've missed that are counter). 

I think it is more likely we should examine how we can be enabling everyone interested in this community work to be joining the individual teams and working groups that they are interested in. AS you've said, the CommComm itself is like the TSC, it's sort of the organizing body over these initiatives that are happening that should feel agency to operate and move on work. I think we've not managed expectations around how much work there is available to people and how they can participate in CommComm ecosystem of work without necessarily having to attend CommComm specific meetings and be a member of -it-. A prime example here is the User Feedback initiative. @dshaw and @mikehostetler have been driving this work, and we discovered that there were bottlenecks due to them not being CommComm members, so we were working to address that through there being CommComm 'champions' to help with removing any barriers--being a liason and not in charge.

**Comment by Tiriel** [comment]
@hackygolucky Thanks for your insight!

Two quick things:
> Deterring eager contributors is not the way to do it(I think is what people are feeling here).

That was absolutely not my intent, as said before. I don't want to turn people away, and I'm sorry if that's how it felt. I don't want to absolutely stop people from contributing or stop observer applications forever.

> My initial thoughts on this are that I don't think a pause on observers solves the problem that we need to address. 

You are absolutely right. As I said, it's not meant to last, nor to solve the problem. Ly suggestion was merely meant to provide a way to keep things clean while we think about new processes. Much more like a temporary patch.

Anyway, I'll just refrain from commenting now, I don't want to be the one monopolizing the convo, and I'd very much like other thoughts on this. I just felt like I had been misinterpreted and I want to be clear about the fact that I mean absolutely no harm, just to help things moving forward.

**Comment by rachelnicole** [comment]
Hey @Tiriel! 

I am really appreciative of how engaged you are with CommComm first of all! I'm glad you've taken such an interest in helping out the community. 

I agree with all of @hackygolucky comments, and think instead of worrying to do about the scale that we're growing at immediately, instead look at the ways that we can best utilize the people that we have coming in. People are getting interested in the CommComm now more and more because we're making progress and they clearly want to be a part of it. 

Like Tracy said & like we discussed in previous meetings, I think we should absolutely find a way to encourage observers and members to find things (working groups and other engagements) that interest them specifically about what we're doing and help them find a way to best participate in that way. I also think that'll alleviate a lot of your concerns about too many members / growing too quickly, because there's never too many members if there's always work to be done. 😸 

That being said, do you have any suggestions on ways to better onboard new users perhaps so it feels like a better experience / so we're best utilizing our community?

**Comment by fathyb** [comment]
Hey @Tiriel. I +1'd @tobyfarley comment because it was my first thought when reading the issue. Just in case I would like you to know I don't feel offended at all and find some remarks on it interesting (which I first misunderstood).
After reading the other comments I decided to give my two-cents as a new observer. (1pt about security, the others about the new observer experience)

1. The security concerns are totally legit. If I just silently participate to all meetings for 6 months, do I become a member? At a large scale giving **member access to anyone** who as attended all meetings without any interactions seems dangerous. Especially for a such large scale project as Node.js.

That's the only comment I have about the original issue as I have a pretty limited knowledge of the subject. The rest are a few suggestions in response to @rachelnicole.

2. **I'm new, what should I do?** I think that we should give more indications to new users. Since I came here most of the discussion were meta, and my first comment is about a meta issue. And I still have no real idea about were to start.

3. More triage. I think that issue could be more triaged, with labels. For example as a new observer I could look for "good first issue" labeled issues. I can only find 3 open, maybe there are only 3 good first issue, but I think **more labels could help see clearer**.

4. **Do we actually need help?** Really, just saying "No observers are needed right now, but you can try again later/subscribe/be notified" is enough if not. If it is the case then they are probably other technical groups/committees to help. If I came here in the first place it's because **I felt like help is needed**, else I can just look for another block on the Node.js community to help, and I will still probably find some awesome people from here. If we need help we have to own it, like "Thanks for joining us, your help is appreciated. Here is a list of topic that need feedback/more people involved : ..". My vision is pretty binary on this point, either you need help on the moment, either you don't. The most important is to be polite about it but that's it.

5. The `GOVERNANCE.md` is fine, but maybe a more accessible document could help? Generally **if you need [RCF 2119](https://www.ietf.org/rfc/rfc2119.txt) to understand it I don't consider it human friendly**. Don't misunderstand me, it's great legally and it is a universally understandable document. It should be the reference. But it's boring and can be hard to understand for some non-native English speakers (especially if you are a developer and you have learnt english by coding). I'd love to see a more accessible document listing for example what is an observer, what role/rights/duties they have, why do we need them and the difference with members. Just that could help people feel more welcomed. (I'd be glad to make my first PR about that)
I was really feeling awkward in the meeting, I wanted to answer questions and give my opinion but I didn't because "I'm an observer, I should observe" (I still don't know to this day, I swear I looked all the markdown files looking for answers).

Again, this is a new comer vision, and I've written this quickly to not limit my interactions here to a +1. And also I'm not a native speaker either, I don't mean to offend or troll on sensible subjects.

**Comment by oe** [comment]
Just my 2 cents, I agree with a lot of what has been said here. In my opinion, the initial conception of the Observer role as it stands is flawed, as it basically implies "you can only contribute to our efforts if you're an observer and then later a member", which is not a position we want to represent. It's definitely mandatory to revise the path to membership and the different positions within our group, ideally simplifying them as much as possible.

Another important issue is establishing a firm position on contributions. We _need_ to make it clear that you don't need to be a member to contribute. Maybe this can be accomplished by redirecting interested folks to our initiatives (on which we should generally shine a brighter spotlight). This should, IMO, be a large priority within our group.

As I see it, and as I've previously experienced it within other grassroots initiatives, this is a critical time during which we've gained an initial foothold and during which we need to adapt our internal structure to be eligible in the long run, or otherwise it may fall apart much more quickly as we've built it up.

**Comment by Tiriel** [comment]
Wow, thanks everyone! That's what I hoped, some discussion around this.

> That being said, do you have any suggestions on ways to better onboard new users perhaps so it feels like a better experience / so we're best utilizing our community?

@rachelnicole I have a few, but for the main one, I've been beaten to it by @oe and @fathyb !
Like I said and others said it too, I think the main problem is that people think they have to become Members to do things with the ComCom. Not only to participate in meetings but to participate at all. The main thing would be to triage newcomers to see what do they want to get involved with and redirect them to the proper teams or WG. The ComCom repo itself doesn't hold that much work for newcomers, and it isn't clear at first sight what one can do with the ComCom to help.

For that, on a related issue, maybe it'd be a good idea to have all the ComCom Members champion or co-champion at least one initiative (maybe except the co-chairs which have enough on their plates already with this position, and the Foundation/TSC representatives). 
I see many benefits to this:
* The ComCom would really be the organizing and coordinating place
* The Members would have an easier time recruiting and triaging newcomers
* What being a Member means would be clearer in terms of implication and role
* If the role of championing, being a relay, is made clear enough, it would make it clearer for users that you don't have to be a Member to get to work with the ComCom

Of course, that also implies redefining the path to becoming a Member, like @oe  and @fathyb said. But that would also make it easier to "quantify" if someone can go from Observer to Member: having launched/championed an initiative for some time is at least a better indicator than simply attending, and implies a bit more work. And I can see some easy ways to onboard people with that.

Again these are my two cents, and I do hope I'm not offending anyone. But thanks a lot for your thoughts!

**Comment by tobyfarley** [comment]
My opinion is that there needs to be, and there currently is, a clear path to become a member of the committee. For good or bad we need to honor that for current observers. If there needs to be a change to be make it more restrictive it needs to be done concurrently with the current policy in place and implemented at the time of adoption and not mid stream. 

Also I think it antithetical to the purposes of the CommComm to be looking at ways to exclude people from membership or limit the number of members of this committee especially at this time. I think we should appreciate that there are people willing to join and let this play out organically. We are experiencing a period of growth initiated by a membership drive at Node Interactive and it is my opinion that the trajectory of growth will taper off in the next few weeks/months.

**Comment by mhdawson** [comment]
My 2 cents.

I agree with the comments that the main focus should be on helping people get engaged in the initiatives and working groups as leveraging the time people have to contribute for the project is the most important thing in my mind.  If somebody has time to contribute let's make sure to welcome them in and help them do that.

I like the idea of asking members to be leading/championing one or more efforts but I also don't want to make this something that deters people from getting involved.  I think building up the contribution expectations for members over time (ie beyond just attendance) is a good idea, but I don't think there is an existing problem that would make us rush that.

**Comment by chowdhurian** [comment]
The issue in the original comment has been addressed with the membership restructuring efforts.

I'm closing for now, but do reopen if needed!
