### ISSUE TITLE
NodeJS Africa Comm-Comm 

### ISSUE THREAD

**Issue by codeekage** [nodejs/community-committee#237]
A way of getting Africa more involved in JS and NodeJS. 

Having it's working group, organizing meetup and making feel more involved in decision making too.

**Comment by flickz** [comment]
This is a great Initiative, as a Nigerian, many NodeJS developers here have no idea what is going on with Nodejs Governance and contributing to the community. We can take this on @codeekage, What do you think?

**Comment by codeekage** [comment]
Sure we can!! we just need formal approval from NodeJS, so we can kick it off.

**Comment by flickz** [comment]
I think been here makes it formal, this is an open initiative not a corporation or something. Although there is a need for support.

**Comment by codeekage** [comment]
Would like to go on with further plans and spreading the news of the arrival of NodeJS Africa? 🙏

**Comment by codeekage** [comment]
We could talk some more on twitter?

**Comment by flickz** [comment]
Yeah sure [@oluwaseunOmoya](https://twitter.com/oluwaseunOmoya)

**Comment by oe** [comment]
@codeekage What exactly would you like us to discuss about this in the meeting? A couple of bullet points would be nice since our time is quite limited. 😅

**Comment by codeekage** [comment]
* How can successful conferences, meetups, hackathons and workshops be held to help increase the knowledge of NodeJS in Africa??

*What amount of support do we have to give to assist people in Africa have a successful community?

*What acess level can we grant them to help them contribute fully and have a wonderful insight of open source? 

*How can we take over the open sorcerers in Africa to be fully commited to writing just NodeJS? 

These are some few questions that will get it started and make it really successfully. I am 100% ready to contribute into making it a success in Africa.

**Comment by codeekage** [comment]
Thank you for adding issue #237 to the cc-agenda.

**Comment by hackygolucky** [comment]
What a cool idea! Because of governance language, we may want to figure out another name for this(it is legal language) and the nomenclature moving forward–in case other communities are inspired by this good work. The idea of supporting individual communities that are doing really awesome stuff is a great idea for working groups in the Community Committee.

**Comment by codeekage** [comment]
@hackgolucky I think it should operate within Nodejs projects and it's repository.

It will be super awesome if you'd help come up with a more super awesome name..🙏😀

**Comment by kinsomicrote** [comment]
This is interesting and I will like to be part.
I'll be interested in knowing the requirements and the commitment involved.
I have been up and down looking for a good way to contribute to Node.js projects, this looks like one.

**Comment by oe** [comment]
Hi @codeekage! We discussed this in today's Community Committee meeting (ref #238). Assuming we're understanding your issue correctly, here's a couple of things the Foundation can do to support your efforts:

- In order to kickstart some great meetups, the Evangelism Working Group has made a [Meetup Starter Kit](https://github.com/nodejs/evangelism/blob/master/documents/meetup-starter-kit.md) that you can take inspiration from.
- The Foundation can provide you with free stickers for your meetups! Send an email to zkeaton@linuxfoundation.org for more information.
- If you want, there's an ongoing effort around community ambassadors. If there are any interesting conferences happening in Nigeria or elsewhere in Africa, you can probably try and figure something out together with us and the Foundation!

Apart from that, unfortunately the Community Committee doesn't currently have the resources to actively support this effort in an official capacity, but you're very welcome to ask us for help in case you have any questions!

**Comment by codeekage** [comment]
Thank you very much for addressing the issue! for now, will only love to be part of the evangelism working group and as an ambassador of NodeJS foundation Africa.

Will be more than happy to get stickers from the foundation !!!!!!!!!!

**Comment by bnb** [comment]
This seems mostly resolved, and has extended into several other issues. Going to close for now ❤️
