### ISSUE TITLE
Re-creating official secretary role

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#241]
At one point in the past, we had an [official secretary role](https://github.com/nodejs/community-committee/issues/64). With our previous election for CommComm chair, the role got folded due to lack of individuals to hold it. At the time, it wasn't a massive issue to not to have an official secretary, but as time has proceeded our workload has increased with the addition of new projects/initiatives and more observers and members engaging in the Committee.

I'd like to propose that we reinstate an official Secretary role. The individual(s) who take on this role would be tasked with:

- Taking meeting minutes for each CommComm meeting
- Submitting a PR with those meeting minutes into the CommComm repo once the meeting is over

Something that we probably need clarity on before electing a secretary is whether or not they need to be an existing CommComm member or not. I don't particularly mind one way or the other, but I do see it as a way to significantly contribute to the Committee - but it is certainly also a non-trivial commitment in terms of time.

**Comment by Tiriel** [comment]
This does look like a good idea. I hear you typing every time, it must be pretty hard chairing and writing at the same time. I don't know how exactly it will be done, and I don't know if I'm sufficiently fluent in English to understand everyone properly, but if no native speak wants to do it, I'll apply. But I'd prefer if someone else with better abilities would do it.

**Comment by codeekage** [comment]
Awesome!! what are the criteria for the position?

**Comment by JemBijoux** [comment]
I'm always happy to help take the notes during the meetings, it's one small way I've been able to contribute a bit. (But I won't stop anyone else who might be eager too.) Just one or two quick thoughts...

I've noticed it can be tough to both take notes and also handle the roll-call / attendance, so anything we can do to cue up the names of attendees/observers/etc ahead of time is helpful (especially since we're doing introductions a little quicker now). I'll try to get in there at least a couple minutes early next time and start jotting down some of the names on the call right away.

Also: the fact that we ultimately output the notes on github as markdown makes using google docs a little awkward. Would love to hear if there's a collaborative markdown solution that's easy to use, but I acknowledge that docs is at least free and accessible. No matter who is on notes, there's always a little awkwardness while trying to format bullet items or links. 

@bnb I hung out near your Twitch stream one night as you were getting the note template all put together. Seems mostly straightforward, though you were still doing some work manually adding issue links. Would you still be the one putting the agenda together?

**Comment by mhdawson** [comment]
I agree that the formatting of google docs does make it harder to keep it in markdown but don't have a better suggestion.

**Comment by bnb** [comment]
@JemBijoux so, @mhdawson has mostly automated the issue, agenda, and doc creation - it's super convenient now. Basically little/no effort on our end.

I will also suggest trying out this Google Apps script - I use it almost daily for my own work to convert a properly formatted Google Doc into Markdown. @mhdawson we may want to investigate its usefulness to us.

https://gist.github.com/bnb/a02712c3f65d18d4ff2c55fc8bab7ace

**Comment by oe** [comment]
I'm definitely +1 on this, even if only for the timely PRing of meeting notes.

**Comment by mhdawson** [comment]
My approach has been to try to capture the meeting minutes in markdown in the google doc, but it does sometimes fight you so finding a better easier way could make sense.

**Comment by maddhruv** [comment]
I am not a member of CommComm, but would love to help.

**Comment by chowdhurian** [comment]
This was discussed in #261. @JemBijoux has kindly accepted taking on this role! 🎉 The door is open to **anyone**, members and observers alike, who wants to help out.

**Comment by codeekage** [comment]
@chowdhurian will love to help too.
