### ISSUE TITLE
CommComm Restructuring Efforts Meeting 2018-03-13

### ISSUE THREAD

**Issue by oe** [nodejs/community-committee#253]
Continuation of #234.

Meeting time: __13th of March 2018, 6:00PM UTC__

Previous minutes: https://docs.google.com/document/d/1jVUmEId-McK8Aooenwfm8gDjsaAbisiLDMjQ9PsyYlA/edit?usp=sharing

Local time: https://docs.google.com/document/d/1jVUmEId-McK8Aooenwfm8gDjsaAbisiLDMjQ9PsyYlA/edit?usp=sharing

Invited: @nodejs/community-committee

**Comment by hackygolucky** [comment]
I'm in! Thanks for the hard work of everyone in the meeting prior.

**Comment by Tiriel** [comment]
Will be there!

**Comment by bnb** [comment]
@oe added to the Node.js Calendar 👍

**Comment by mhdawson** [comment]
I'd like to attend but I will be out of the office that day so I'll probably miss it.

**Comment by mhdawson** [comment]
One thing I'd like to suggest for discussion is the introduction of "collaborators" for CommComm.  I know we can't necessarily make the criteria commits, but just like the technical side it can be from contributions being made which just need to be outlined in the nomination. 

This would at least solve a few current problems:
* being able to give people access to repos without having to be a CommComm member
* getting people to the collaboration summits without requiring them to be a CommComm members. 

It also provides a path that supports scaling more easily, 
 initial contributor -> collaborator -> CommComm member.

With the members typically being the most active collaborators (at least that is commonly the case on the technical side).   At this point I'd still keep it so that anybody can join the CommComm meetings as an observer, but work to push actual work into working groups so that over time that is where the real action is.

**Comment by bnb** [comment]
@mhdawson I'm really glad you brought this up, this is very much along the lines of what @oe and @Tiriel were discussing in the prior meeting. I'm definitely +1 as well, and I think putting definition to what a "Collaborator" is will be wholly beneficial for the CommComm overall.

**Comment by Tiriel** [comment]
Aye, that's definitely something along the lines of what I was proposing at first, with the complementary step that new members should actively championning or at least participating in a WG or an initiative.

So that's a +1 for me, and I definitely think this is worth discussing in the next restructuring meeting!

**Comment by oe** [comment]
Meeting Notes are here: https://docs.google.com/document/d/1mlk48QmZcGCyJHVRCj_ZorHN3BX_xncQZ5tR-Hvsz6M/edit?usp=sharing

**Comment by oe** [comment]
Link to join the meeting: https://zoom.us/j/150571995

**Comment by hackygolucky** [comment]
Heyo! Following up from last meeting, we had another work session on the calendar for today, but I don't think we had anyone scheduled to lead it. Should we propose a time for next week or the week after to continue this work?

**Comment by chowdhurian** [comment]
Would the same time next week work? If so, I'll make an issue for it.

**Comment by Tiriel** [comment]
Damn, completely had forgotten too. Sometimes next week would definitely be better for me!

**Comment by bnb** [comment]
@chowdhurian that would work for me. I suggest creating an issue and proposing the time but being open to it changing 😄

**Comment by chowdhurian** [comment]
Closing this, as a new issue has been opened for the next meeting to continue the Restructuring Efforts
