### ISSUE TITLE
Diversity/Inclusivity Initiative

### ISSUE THREAD

**Issue by Tiriel** [nodejs/community-committee#260]
Hey everyone!

There's something we've been talking lately a bit (like in #117 ), that I really want to be taken forward. I'm talking about Inclusivity/Diversity in the Node.js Project/Community.

I realize I may not seem to be the best fitting person to champion this, as I may not appear to be a primary target for inclusion at first (though I am in fact), but since thing currently aren't really moving, I'd like us to send the message that we are and will continue working on the matter by creating an Initiative.

**What I have in mind for now:**
- Gather people concerned by inclusivity, whether directly or not
- Define clearly what is inclusivity, as discussed in #117 
- Get some user/community feedback from people concerned by inclusivity (what they expect form the project, what are there struggles within the community...)
- Continue to raise awareness and promote diversity inside the project's Core, WGs and teams

Of course, I'm deeply open to suggestions, and if some people want to get to work on this with me, I'd like to get this officially sanctioned by the CommComm

**Comment by Tiriel** [comment]
Hey everyone!

So, following yesterday's meeting, I'd like to detail a bit some things about this, what my plan is for now, and get people who want to help make a sign. From the people who have expressed interest in this issue by plus-one-ing or in yesterday's meeting, I'll take the liberty to ping @mhdawson , @JemBijoux , @jakeNiemiec, @bnb and @hackygolucky . But as always, everyone is welcomed.

It may seem too much to some, but since we are not exactly talking about code but philosophy, I'd like to state that this initiative is of the utmost importance to me for one very simple reason: I strongly believe in changing codes in a group by giving the example, and that __*small streams make great rivers*__. We have the chance to have an already quite open community, and we should take this change to push forward. While I realise this seems idealistic, let's start (again) with our own level and see where it goes.

# Inclusivity / Diversity Initiative
Please keep in mind this is a working document and is intended as a proposal. Contributions and discussions are deeply welcomed.

## Purpose
The purpose of this initiative is to give voice and support to everyone in the Node.js project and community, especially the less represented ones. Its aim is to keep the Node.js community welcoming and make it even more open and representative over time.
While these goals may seem overwhelming, this is meant to be a long-term, ongoing action.

## How?
Several options, in order of priority:
  
 * Make this an official Strategic Initiative or Working group if possible
 * Get feedback from people concerned by diversity, whether because of their gender, ethnic origin, country, religion, neurodivergence, or any other form of particularity
 * Advocate for the inclusion of concerned people in every process and project of the Node.js community
 * Give concerned people the means, places and voices to advocate for themselves
 * Determine more means to empower concerned people inside the Node.js community

As hinted above, one thing of paramount importance is that none of this should be done without the people concerned by inclusivity themselves. No one can truly speak for someone else, especially when the people we speak for have experienced discrimination we have not.

__*This initiative needs to be held for diverse people, by diverse people.*__

## Who?
By the very definition of this initiative, everyone is welcome to volunteer and help achieve its goals. Every contribution, small or big, long or short, is of huge value to this initiative.

**Comment by oe** [comment]
I would like to stall this until the Collaborator Summit in Berlin. This issue brings with it a lot of concerns that we need to keep in mind, therefore I think it'd be better suited for an in-person session, where we will hopefully be able to make some real progress with this. Until then, I'm going to veto this (sorry @Tiriel!).

**Comment by bint** [comment]
one friendly thought, which is if this matter is only discussed to be in-person, then the people in question really ought to be diverse themselves. Otherwise, how will those perspectives be part of the conversation?

**Comment by Tiriel** [comment]
This does raise a very valid point. And while having in-person discussions will certainly facilitate things, we do also need to keep a high level of transparency. We will need to keep things properly balanced, otherwise, inclusivity won't really be inclusive.

**Comment by bnb** [comment]
Nobody said it was _only_ to be discussed in-person, so let's please not go down that path as it will likely lead to derailing the intent of this discussion.

From quite a bit of prior experience across the Node.js Foundation, the various committees, working groups, teams, and initiatives have found that in-person sessions are one of our most valuable assets to get things _started_.

By no means are these events exclusive, and actually work to do the _opposite_–pairing with events that happen with individuals who don't usually have much of a voice in the Node.js project, and by offering the Travel Fund to individuals who are already participating in the project and would like to participate.

The Community Committee _itself_ was started from such an in-person meeting, and has grown to be a functioning and transparent committee working toward improving the project.

Let's not conflate the **extremely valuable** and rare in-person sessions–where interested parties can get a tremendous amount of work done–with being exclusive and homogeneous.

**Comment by Tiriel** [comment]
Thanks for the precision @bnb !
In that case, I think both @bint and myself misunderstood what @oe saif when they were asking to stall this initiative. For me, it meant that no work could be done before the Collab Summit. But maybe that was not what was intended.

If indeed we can still work on this, at least by talking between us, gathering ideas and people of good will, and posing the cornerstone of this being "chartered" as an official initiative/WG, then all the better, and I'll start working again as soon any of you confirms!

*Sidenote:* I'm terribly sorry if some of my messages sound a bit bitter. By reading them again I fear it might be seen as such, but that was not my intent. Got some personal problems these days that may have perspired in my messages. If that's the case and I've offended anyone, you all got my sincerest apologies.

**Comment by bnb** [comment]
@Tiriel I do believe that was the intent of stalling it until the Collaboration Summit.

Some context: There have been efforts around Diversity and Inclusivity inside of the Node.js project in the past–while well intentioned, they ended up being shuttered for reasons that were both internal and external to the project. Several of the CommComm members were involved in those efforts, and still care about Diversity and Inclusivity.

Those efforts failed.

If we attempt work around Diversity and Inclusivity again, it needs to be set-up and managed _extremely_ carefully with an attention to detail and mindfulness. There's a lot of context and lessons learned that can't be as easily communicated digitally.

Doing this in-person will be several orders of magnitude more beneficial to making this effort a success–which is what literally _everyone_ wants–rather than a failure. Not only has in-person work proven to be an extremely important and effective decision making method, it will actually help us _increase_ inclusivity in the discussion. The CommComm is a moderately homogenous group because of how our membership process has been structured in terms of interests, concerns, and background. At events like the Collaborator's Summit, we're able to include people who are interested in Node.js but who don't have that similar set of interests, concerns, and background.

As my own side note, don't worry about it Ben. I know that you're trying to help drive an initiative that you care about. We really do appreciate that from _anyone_, even if we may disagree or misunderstand that person (or vice versa) sometimes.

**Comment by Tiriel** [comment]
Hi everyone!

Not to try to prematurely relaunch anything but I'd like some information re this issue.
Namely, I completely understand that the lessons learnt from past Inclusivity/diversity experience are hard to convey on GitHub, but if anyone has pieces of information on why previous attempts failed, I'd very much like to have them. My twitter DMs are open, and so is my mail (benjamin.zaslavsky[at]gmail).

Just to add some context. I don't want to drop this initiative, and I don't want it to fail/be shuttered. I don't want to repeat past errors either. And there are lots of other projects on the web who might benefit from these learnings too. I don't plan on spreading information about the internals of the Node project. I just want to help spread openness and promote inclusivity as widely as possible.

If this is too much of a problem, I perfectly understand, one only need to tell me.

Thanks for reading!

**Comment by jakeNiemiec** [comment]
@Tiriel The thing is, `Diversity and Inclusivity` means something different to everyone (depending on your life & work experience). 

Personally, I have had the pleasure of working on a team with people from all over the world (currently: 🇧🇪🇪🇨🇧🇦🇰🇿🇺🇦🇪🇸🇬🇧🇷🇴🇹🇼). 

This has been an incredibly rewarding experience because you get to hear about all walks of life -- from the beauty of Ecuador (🇪🇨) to the horrors of losing your parents wilst having to grow up durring the Bosnian War (🇧🇦).

Many American definitions of diversity tend to focus on skin color, sexuallity and gender. **This is also just as needed and valuable**. But, it pains me to see my Bosnian friend's identity reduced to `cis white male` by upper class city-dwellers who wouldn't be able to name half the flags above.

**My personal idea of diversity is a nice blend of these two things.** I would like to know if this aligns with what you think.

I think that the biggest obstacle to inclusivity/diversity is it's nebulous definition. While we wait for the Collaborator Summit (which I cannot attend), perhaps @Tiriel, @bnb and @oe could detail what inclusivity/diversity mean to them personally and what exactly is lacking about the current _"homogenous group"_. I really hope that we can get a clear picture what we all want individually.

**Comment by Tiriel** [comment]
Thanks for your perfect insight @jakeNiemiec !

You're perfectly right, diversity is really a difficult thing to define. But if I had to define what it *means* to me, it'd be along these lines:
**I don't care who or what you are, or where you come from on a physical, metaphysical or social level. I don't care who you love or don't love, what are your political and religious beliefs or lack thereof. You are deeply and equally welcome here, as long as you're willing to share some things with us in peace and openness.**

This being said, I don't think that's the main problem here, and that's what I wanted to learn more about. Sadly, we do have a pretty homogenous group at least on a superficial level, mainly composed of the infamous "white cis straight male" group. But when you look closer, this is not so the case. I for one am not entirely white (it depends on who you ask), I don't know everyone but there's a good chance we have non-cis, non-straight people, and in any case we have "non-male" people (if you stick to the "white cis straight male" problem), and I'm fairly sure we have people from very diverse social backgrounds and origins.

Furthermore, I don't want to go and look really closely at the composition of this group, as I fear we might end up doing quite the opposite of the definition I gave above and taking specific people in, instead of taking everyone. But this is just my opinion.
  
But indeed, this definition will be one of the main things to discuss! And again, I don't want to hurt or offend anyone. Right now, I just want to make my own "preparatory search" on what has been previously done, well or not, so I can learn, and prepare the Collab Summit.

Cheers!

**Comment by bnb** [comment]
I'd like to suggest we cut this discussion a bit short and discuss it _at the Collaborator's Summit_.

There definitely seems to be multiple kinds of context and differing familiarity with the subject of inclusivity and diversity, and we are doing ourselves a disservice by discussing it in an asynchronous manner. From my outsider experience with the Inclusivity WG, this was one of the things that caused some major issues and eventually led to the WG being shuttered.

Let's follow through with what we've already agreed on doing as a Committee and put this discussion on pause until the Collaborator's Summit.

**Comment by Tiriel** [comment]
@bnb  My apologies, I let myself pulled into discussing details instead on focussing on getting background, which your reply partially provides.

Since indeed this was discussed and approved, I've edited my previous reply to be masked until the Collaboration Summit.

**Comment by Tiriel** [comment]
Quick update, pending more very soon.
This subject has been largely debated during a full workshop session yesterday at the Summit. We have a lot of work, lots of concrete propositions. I'll open a new issue today to talk about this.

Closing this meanwhile.
