### ISSUE TITLE
Plan Collaborator Summit Berlin 2018 Topics

### ISSUE THREAD

**Issue by dshaw** [nodejs/community-committee#270]
Agenda building for [Collaborator Summit Berlin 2018](https://github.com/nodejs/summit/issues/60) has begun. Many of our current active collaborators, including myself, joined at the last Collaborator Summit in Vancouver at Node.js Interactive. Let's come up with topics we should cover there.

**Comment by oe** [comment]
I'd definitely like to iterate more on the membership question, if it still exists by then (hopefully it doesn't). It might also be nice to do some cross-cutting of concerns with the represented TSC members.

**Comment by Tiriel** [comment]
I'll definitely make what I can to be here, and I'd like to have a chat about the Inclusivity Initiative ( #260 )!

**Comment by codeekage** [comment]
Will love to be there!!

**Comment by codeekage** [comment]
Who will love to visit Nigeria, we could host the next Collaboration Summit??? Crazy THought THough!

**Comment by chowdhurian** [comment]
I also joined at the last one in Vancouver (🙌 @dshaw) and I'm wondering if the work done in Vancouver will be similar to the intended outcomes for Berlin. There seems to be a lot more happening (compared to back then) in terms of initiatives ([i18n](https://github.com/nodejs/i18n ), [website redesign](https://github.com/nodejs/website-redesign ), [user feedback](https://github.com/nodejs/user-feedback), [badges](https://github.com/nodejs/badges)) and a big benefit I anticipate is that meeting (re-meeting! 💯) collaborators in-person could make easier the multi-timezone remote collaboration that is the daily reality of [NodeJS](https://github.com/nodejs/).

**Comment by bnb** [comment]
@chowdhurian I think several things will be different. Are you talking about when we had a round-table just after Code and Learn? If so, that was more of a thing to get people involved - the Collaborator's Summit was the next day. I know a few individuals who came to the round-table also came to the Collaborator's Summit, just can't remember if you were one of them 😅 

I do think that this Collaborator's Summit will be more focused on individual efforts rather than a group meeting (so, for those who were there, more like the Collaborator's Summit at Node.js Interactive 2016 rather than the one at Node.js Interactive 2017). This will hopefully allow us to focus our efforts on individual working groups and initiatives and achieve decisions quickly 😄

**Comment by chowdhurian** [comment]
Adding this [issue](https://github.com/nodejs/website-redesign/issues/29) to pull in topics as they're gathered from the website-redesign initiative!

**Comment by Tiriel** [comment]
Closing this as the event has passed!
