### ISSUE TITLE
Initiative for Nodejs Community Chapters

### ISSUE THREAD

**Issue by WaleedAshraf** [nodejs/community-committee#280]
Purpose of this initiative is to have a collaboration/partnernship between Node.js Community Committee and NodeSchool Chapters (could also be some other local community).

**Benefits for Node.js Foundation and ecosystem:**
- Reach more people/developers and Involve them in the community.
- Getting core collaborators.
- More involvment in Mentorship initiative, to get more mentors and menttees.
- Getting feeback from public for User Feedback initiative etc.
- Discuss/fix Node core issue on NodeSchool events/workshops.
- Serve the purpose of Community Committee to reach as much people as it can.
- Give support to local initiatives to come forward and participate.

**Benefits for NodeSchool Chapters:**
- Opportunity to collaborate with more Node.js / Javascript developers and community members.
- Organizers can easily take input/feedback from Node.js Foundation members/collaborators.
- The chapter can easily invite people from Node.js Foundation as speaker.
- Easily advertise/publicity of NodeSchool chapter events/workshops through Node.js Foundation. This can be done through opening an issue in relevant Node.js Foundation repo for discussion or through social media etc.
- The chapter can add Node.js logo on its website and add text like "in collaboration with Node.js Foundation."
- The chapter can easily request for Node.js swag for events or permission to print it by self.
- The chapter can take feedback from its event/workshop attendees and communicate it to Node.js Foundation members easily.

**Why is it needed now?**
I think this can be very helpful to @nodejs/community-committee. 
CommComm is one of the most active WG. We have weekly meetings, an awesome team which actively respond to issues and listen to public concerns. But I think it also needs a **physical presence** like chapters. This would help the community to have easy access to people from Node.js Foundation.
Having such chapter gives WGs members a platform to easily interact with Node.js users/public which I think is really important for CommComm WG (maybe not for other WGs).

Reason to select NodeShool is that many of us (Node.js Foundation members) are already running a local NodeSchool chapter and it is one of the most common Node.js Community.

**Related Issue in NodeSchool/Organizers:**
-  [Collaboration with Node.js Community Committee / Working Group Members](https://github.com/nodeschool/organizers/issues/520)

**Related Issue is CommComm:**
- [Begin Documenting Partner Communities (and what that means)](https://github.com/nodejs/community-committee/issues/326)

**Suggested process for this:**
This collaboration would go under [PARTNER COMMUNITIES](https://github.com/nodejs/community-committee/blob/master/PARTNER_COMMUNITIES.md)

1.  Chapter would 
    - Have a Code of Conduct.
    - Have a Moderation Policy.
    - Have a Node.js Collaborator. (Many NodeSchool chapters already have.)
2. Chatper would be listed under a secection in PARTNER_COMMUNITIES.md
3. Chapter would be allowed to put Node.js logo on it's website.
4. Node.js Foundation would create a sepearte repo like "Community Chpaters" where organizers can open issues and get help from Node.js Foundation members.
5. "Community Chpaters" repo would have a readme with general instruction and list of all Node.js related communities around the world and how to reach them.

**Similar issue which have been raised in past, but staled:**
Same issue has been raised in different ways in different repos, many time.
- [Evangelism initiative](https://github.com/nodejs/evangelism) as its purpose is to 
> Bring discussions to a wider audience and attempt to grow the community through positive, supportive messaging.
- [Reviving Evangelism Working Group](https://github.com/nodejs/community-committee/issues/275).
- [community-events](https://github.com/nodejs/admin/issues/76) initiative which was started under CommComm.
- [Local Initiatives](https://github.com/nodejs/evangelism/tree/master/documents/local_initiatives) under Envgalism team.
- [COMMUNITY [GLOBALIZATION, DIVERSITY]](https://github.com/nodejs/community-committee/issues/268).
- [Diversity/Inclusivity Initiative](https://github.com/nodejs/community-committee/issues/260).

**How this is different from previous initiatives like "community-events" :**
Previously, we tried to manage community events/chapters by our self which is big task it self and most of the time, no one was able to give time/effort needed. By collaborating with existing chapters like NodeSchool would save us time/effort in managing the events/workshops/talks everything.

**Comment by maddhruv** [comment]
As we get some meeting with NodeSchool people for website redesign getting started content and other documentation contents, I think it would be beneficial collaborating with NodeSchool officially/unofficially starting up Community Chapters

**Comment by inidaname** [comment]
Starting a Nodejs community chapter, from what I have read so far its a good thing this should come under ComCom, that's if it won't be too much on them already.
The option of using Nodeschool, I feel why the [community-event](https://github.com/nodejs/admin/issues/76) failed **if I can use the word failed**, is lack of participation one way towards this can easily and successfully be achieve with Nodeschool adoption but isn't Nodeschool already effectively handling this _treat this as a request for enlightenment._

**Comment by WaleedAshraf** [comment]
@inidaname You are right and collab with NodeSchool would be helpful for both sides. It'd give NS members a way to speak/convey message from Node.js and Node.js WGs to the community and on the other hand, Node.js can get easy access to live community in terms of getting feedback and dealing with Diversity/Inclusivity/Globalization/Evangelism etc.

@bnb can we add this in cc-agenda?

**Comment by PatrickHeneise** [comment]
Just my thoughts based on my experience of running NodeSchool in Barcelona: NodeSchool is great, but it mainly serves two specific groups of people: the ones who want to get started with node and the ones who want to teach. I don't think NodeSchool serves the purpose of "group building". People joined NodeSchool once and either dropped it or moved on to the NodeBCN user group. One of the bigger issues of the NodeSchool chapter repos is GitHub itself: there's an assigned maintainer and there might be others who want to organise an event but can't because it's already assigned and the maintainer won't merge the PR for example.

I'm personally interested in a directory of Node.js users especially in small towns and remote places. I'm traveling a lot recently and would like to join them and maybe offer my help with talks, organisation experience etc, as long as there's an easy way to reach out before (meetup.com is not easy). Not sure if that fits into the scope of this issue, just how I feel about it.

**Comment by maddhruv** [comment]
The Community Chapters would be focused upon not only with getting started with Node content but also with going ahead with JS and Node like - learn skills, t&t with Node and other introductions, also organizing Meetups, conferences, summits official/unofficial with NF

**Comment by codeekage** [comment]
I think JS/Node.js content should be developed by Evangelism WG members probably under the CommComm.

That might probably bring the WG back to life. Don't know if that makes actual sense?

**Comment by PatrickHeneise** [comment]
For me it would. :)

**Comment by WaleedAshraf** [comment]
@PatrickHeneise I agree. But I think it also depends on how NS is managing events. If it's a **Level: Beginner** talk/session than most of the attendees would be starter. If it's a **Level:Advance** talk/session than it would have a similar audience.
Well, this can be managed based on how talks/session are being arranged. We can deal with NS related issues aside. The good thing is that this would give Node.js a platform to communicate/have meeting/talks/sessions directly with users and much more.

About directory: Yes, that has been also raised. I personally felt that there is a need for a global directory(optional to signup) from where people can get in touch with the local community.
Related issues:
[Node.js People Everywhere (npe)](https://github.com/nodejs/community-committee/issues/184)
[nodejs - members directory](https://github.com/nodejs/community-committee/issues/227)

But this ^ also relates to having a chapter/community. For example, if there is talk/session arranged by NS, the organizer can ask attendees to fill the member's form (optional). And later on, it can be followed in all NS chapters around the world. It would create a huge directory of Node.js users/starter/mentors/students everyone.

**Comment by PatrickHeneise** [comment]
That looks interesting. One issue I see here is the central "organiser" role, means many need to rely on a few to be online/respond/etc. I've seen a lot of struggle in the past with "ownership" over the organiser role, a directory would resolve that. Signup from NodeSchool would definitely help to get a lot of people into the directory fast.

**Comment by WaleedAshraf** [comment]
@hackygolucky would we represent this repo/team as CommComm Initiative or sub-working group?

**Comment by maddhruv** [comment]
Can you get me on board? I am willing to lead this wg, if CommComm can allow me!

**Comment by PatrickHeneise** [comment]
@WaleedAshraf that was pretty much the state of the `events` repo, except there was never a team for it. Will try to help whenever I can though to make it work this time.

**Comment by codeekage** [comment]
I don't think much can be done on this, till we know how working groups would function under the CommComm. 

In the past, many WG under the CommComm has failed and that should be something we should avoid, allowing this not to fail. In as much we all want this to work we should definitely get the persons actively involved in this and fully instrested in it, probably have a meeting and how we can structure this not to fail too... But let's watch out for the decision on the CommComm Membership and WG before acting on this.

**Comment by WaleedAshraf** [comment]
@codeekage @PatrickHeneise  I agree.
that's why I have opened an issue in nodeschool. To notify/involve people who are interested. I do realize that if there aren't enough people supporting this initiative than it would be just like previous one.
I'll keep this issue updated with feedback from nodeschool organizers.

@maddhruv I appreciate your interest, but right now, even I'm not sure who will be leading this, and how we will select a leader. Keep following the discussion here. 👍

**Comment by codeekage** [comment]
Awesome @WaleedAshraf  but it will be more awesome if we could work on how it will be structured, function and purposes before presenting it to the CommComm. I propose a meeting before the next CommComm meeting, so we can plan on it properly before getting more persons involved. From issue #520 in @nodeschool/organizers.

**Comment by WaleedAshraf** [comment]
Hi everyone,
Those who are going to attend Collab Summit, I'd love if someone can discuss and get feedback on
[Initiative for Nodejs Community Chapters](https://github.com/nodejs/community-committee/issues/280)

There is also a related issue in NodeSchool Organizers repo, where many organizers have shown interest. [Collaboration with Node.js Community Committee / Working Group Members](https://github.com/nodeschool/organizers/issues/520)

I assume many people from NodeSchool and other communities would be present at Collab Summit so it'd be a good time to discuss. There is no plan on what should be done right now. So just getting feedback and opinion from others should be enough.

@nodejs/community-committee

**Comment by Tiriel** [comment]
I don't know if there was any talk about that in a session at the summit, I must admit I can't remember.

Can anyone provide input on this? cc @nodejs/community-committee

**Comment by WaleedAshraf** [comment]
@bnb can discuss this in next commcomm meeting?

**Comment by hackygolucky** [comment]
My recollection of discussing this work was that we can list best practices of running events throughout the world to help support organizers. Empowering the best practices and how we can help those groups, running independently of this organization(such as Node.js Africa), is what we can do in here. As we've discussed many, many times, is that we should not be providing a structure for events around the world internal to this project because we can't provide the resources and vetting required to hold these groups accountable to being official to the Node.js project.

What we've reiterated in these conversations, both in issues and in meetings, is that you don't need the Node.js project to have the org you are talking about. You could do this very similarly to NodeSchool, which intentionally does/did not operate under the Node.js project to have agency and not be held to the same governance structure.

**Comment by bnb** [comment]
I'd like to echo what @hackygolucky said, plus add that even if we did agree that we wanted to build out such a project we wouldn't have the ability to execute well enough on it to actually provide the infrastructure needed.

Beyond even being able to execute on it, I'd argue that Node.js has been fundamentally rooted in grassroots community. From the modules ecosystem to grassroots events like NodeConf and NodeSchool, trying to figure out how we can mimic that inside of the project is a mistake because it takes the opportunity away from the dozens of grassroots Node.js community events and organizations around the world.

The project has always provided frameworks to do really cool things and build on top of those cool things – building out resources that those who are interested in running events can take on would be an incredible feat, and definitely something we can maintain and iterate upon over time. For better or worse, Node.js as a project community is one of the leaders in being forward thinking in terms of _people_ – this is yet another way to continue building out that and lead the way for innovation around _people_ within our ecosystem.

**Comment by WaleedAshraf** [comment]
@bnb @hackygolucky I agree with both of you but I'm not sure if there is a way for a community to have minimum collaboration with Node.js that it doesn't come under Node.js Foundation IP but still can use its name for many use cases (few of which I mentioned in issue description).

Other than that, I see a number of NodeSchool organizers interested in this collaboration which you can check here: https://github.com/nodeschool/organizers/issues/520

And with this "[Begin Documenting Partner Communities (and what that means)](https://github.com/nodejs/community-committee/issues/326)" issue, I'm not sure if a NodeSchool chapter can represent it self as "Partner Community" if it fullfil the requirments? 

- Adherence to the Node.js Code of Conduct
- Adherence to the Node.js Moderation Policy
- Participation of a Node.js representative as a moderator (likely an org member, or possibly a TSC/CommComm member?)

**Comment by hackygolucky** [comment]
Yeah, this is tough @WaleedAshraf. 

Moderation with Node.js has the constant challenge of how much work it takes to know the context of a particular area that they are moderating in. It's part of why the Moderation team and the Admin group have lots of conversations around what can be considered a part of the Node.js project because we barely have enough people to moderate our existing spaces. That ensures we maintain trust and quality of experience. This is one major reason why we say that we want to help encourage ecosystem folks excited about Node.js, but it is tough for us to say it's a part of the Node.js project because we can't ensure the guidelines and governance are being adhered to and enforced.

 I think the same goes for Parter Communities. When we're saying we're partnering, we're implying some sort of vetting. Which means people trust that they can go to those events/communities and receive a similar level of care and experience.

**Comment by codeekage** [comment]
Moderation on the Node.js project has always been something we take into consideration before performing or carrying out any project at any level which is something I really do love about the Node Team. Our CoC and how members try to carry out all by-laws even when they are off the project is super Awesome! 

If moderation and we not having enough folks to help enforce this task? Using the resources we have should do it... which are already existing collaborators. If every member at the top-level community consider themselves as a moderators of the Node.js Project we can do more in moderation than we are already doing. 

Using the Outreach-Committee:

Context around this, is yet to be established but we could empower this team to also carry moderation amongst partner communities. 

I think working on moderation and how we can do more with the little we have now should also be discussed in the next CommComm meetings. 

@hackygolucky @bnb @manil @WaleedAshraf

**Comment by codeekage** [comment]
@PatrickHeneise I get your point and how this may seem to appear but that's clearly not the case since the Node.js Org have invested so much in diversity and inclusivity saying:

> To me, this reads like an issue of trust. 

is completely not true. 

We are only careful with how we manage onboarding new initiatives and knowing how we can manage them in a long run. 

If language around managing them and entrusting responsibilities to folks as representative of the Org to organize and manage communities, don't you think it makes sense to be sure that the representative is able to uphold the image of the Org and maintain our standards, CoC and moderation policies?

**Comment by PatrickHeneise** [comment]
Thanks for clarifying, @codeekage. This is just how I feel about this issue.

I do agree that organisers need to upload the image of the org, as you say. But how should people be recognised for their efforts? How can someone with the help of the Node.js Org start an "official" meetup or event in a city?

In regards of diversity and inclusivity offline, the only official Node event is in North America. Before it was at least in Europe as well and more accessible. There's nothing in Asia, even though it's by far the biggest community. How do people engage if they can't afford a flight to North America?

**Comment by WaleedAshraf** [comment]
After little more discussion with NodeSchool Organizers, here is list of benefits that a chapter may get after collboration with Node.js Foundation.

Here are few benefits I think of:

- Oppertunity to collabortate with more Node.js / Javascript developers and community members.
- Chapter Organizers can easily take input/feedback from Node.js Foundation members/collaborators.
- Chapter can easily invite people from Node.js Foundation as speaker if needed.
- Easily advertise/publicity of NodeSchool chapter events/workshops thourgh Node.js Foundation. This can be done through opening an issue in relevant Node.js Foundation repo for discussion or through social media etc.
- Chapter can add Node.js logo on its website and add text like "in collaboration with Node.js Foundation."
- Chapter can easily request for Node.js swag for events or permission to print it by self.
- Chapter can take feedback from its event/workshop attendess and communicate it to Node.js Foundation members easily.

Happy to discuss more around this in out next meeting and in [Partner Communities](https://github.com/nodejs/community-committee/pull/352) issue.

Related issue: [Begin Documenting Partner Communities (and what that means)](https://github.com/nodejs/community-committee/issues/326)

ping @mhdawson

**Comment by WaleedAshraf** [comment]
@nodejs/community-committee everyone at Node+JS Interactive/Collab summit this issue really needs more discussion. So feel free to ping me.

**Comment by WaleedAshraf** [comment]
@amiller-gh can you add agenda tag to this?
Also, if possible, can we discuss this at collab summit?

@chowdhurian @BridgeAR need your comments as you run local NodeSchool?

**Comment by PatrickHeneise** [comment]
@WaleedAshraf will you update the issue with the outcomes and notes from the meetings?

**Comment by amiller-gh** [comment]
@WaleedAshraf, always feel free to add the cc-agenda ticket yourself too 🙂 

@PatrickHeneise, will do 👍

**Comment by WaleedAshraf** [comment]
@amiller-gh @bnb 
With [#412 - Specify requirements for partner communities](https://github.com/nodejs/community-committee/pull/412) merged, can we move forward with this issue?
I'll open a PR with changes in [PARTNER_COMMUNITIES.md](https://github.com/nodejs/community-committee/blob/master/PARTNER_COMMUNITIES.md)

**Comment by WaleedAshraf** [comment]
@amiller-gh @bnb We should either make this update for close this ticket for later discussion.
Let's discuss this in next commcomm meeting and finalize it.

**Comment by bnb** [comment]
@WaleedAshraf was this discussed in that session? 🤔

**Comment by WaleedAshraf** [comment]
I'll update this issue. Thanks for the ping. @bnb

**Comment by bnb** [comment]
Going to close for now since we've not seen forward movement on it in ~6 months. If there is a critical mass of support and we see traction, feel free to re-open.
