### ISSUE TITLE
Please add Jiasm  as a meeting observer

### ISSUE THREAD

**Issue by Jiasm** [nodejs/community-committee#297]
I want to be join the community-committee's meetings. this will be a great thing in my life.♥️♥️♥️

**Comment by Tiriel** [comment]
Please be aware that depending on the outcome of #299 , your request to observership may not get through.

But in any case, we are super glad to have you participate in our work! Don't hesitate to check on the [current initiatives and WGs](https://github.com/nodejs/community-committee#current-initiatives-teams-and-working-groups) to see how you can better get involved, if you have not done so already!

**Comment by Jiasm** [comment]
Okay, i got it, thanks for @chowdhurian @Tiriel 
🙂

**Comment by bnb** [comment]
@Jiasm 👋 

So we're currently undergoing some membership restructuring, and removing having observers as a path to membership. Our goal is to focus more on doing work inside of the different areas that the Community Committee covers–such as Internationalization, Website Redesign, and User Feedback instead of focusing on the more administrative tasks that occur in the Community Committee.

We'd like to give you the choice instead of deciding for you: Would you like to go through with being observer, or participate in the newer approach we're starting shortly?

Happy to answer any questions you may have here! 😄

**Comment by Jiasm** [comment]
hello @bnb ,

I chose this new one. 
I think I can do more things in internationalization *(I come from China)*
Looking forward to its start😄

**Comment by Tiriel** [comment]
Glad to have you working with us!

I'm going to close this since I think there's nothing more to be done here. But do feel free to reopen if there is.

**Comment by Jiasm** [comment]
I can't wait to participate in this great project :) 
awesome.
