### ISSUE TITLE
Elect a Chairperson

### ISSUE THREAD

**Issue by williamkapke** [nodejs/community-committee#30]
Per the Charter, CommComm gets to elect a Chairperson.

> The CC will elect from amongst voting CC members a CC Chairperson to work on building an agenda for CC meetings and collaborate with the Individual Membership Directors the wishes of the CC to the Board for a term of one year according to the Node.js Foundation’s By-laws. The CC shall hold annual elections to select a CC Chairperson; there are no limits on the number of terms a CC Chairperson may serve.

We do not have a predefined process for this - let's get that figured out!
(e.g.: Nominations open for 1 week, voting open 1 week)

**Comment by williamkapke** [comment]
Just noticed that @emilyrose & @jpwesselink are not watching the repo so... PING! FYI!

**Comment by nebrius** [comment]
So to give a little more context to this. The community committee's charter states that [we need to elect a chairperson](https://github.com/nodejs/community-committee/blob/master/GOVERNANCE.md#section-7-elections).

The charter describes the chairperson as:

> The CC will elect from amongst voting CC members a CC Chairperson to work on building an agenda for CC meetings and collaborate with the Individual Membership Directors the wishes of the CC to the Board for a term of one year according to the Node.js Foundation’s By-laws. The CC shall hold annual elections to select a CC Chairperson; there are no limits on the number of terms a CC Chairperson may serve. 

To break down the the role a bit further:
- Create each meeting's agenda. We have a tool to create agenda's called [make-node-meeting](https://github.com/rvagg/make-node-meeting) which makes the agenda creation process a lot easier
- Create the event and make sure it is live-streamed in YouTube. There's a document explaining how to do this _somewhere_, but for the life of me I can't remember where.
- Chair each meeting. There are several sections to each meeting, which you can see listed in https://github.com/nodejs/community-committee/pull/32, and it is the chairperson's responsibility to ensure that the meeting stays on track, sticks to the agenda, and finishes within the allotted time.
- Collaborate with @williamkapke and @ashleygwilliams on presenting things to the board from CommComm that need attention. This part of the role is murkier than the others because there is not existing precedent for this kind of division of labor within the Foundation. It's up to the incoming chairperson and the individual directors to really flesh out what this looks like.

If this sounds like something you're interested in, let us know!

**Comment by mikeal** [comment]
Because this group is still growing, I would recommend setting a short term this time around so that you can return for another election after the group has grown.

**Comment by nebrius** [comment]
> Because this group is still growing, I would recommend setting a short term this time around so that you can return for another election after the group has grown.

Following this train of thought, I recommend we try and get https://github.com/nodejs/community-committee/issues/31 figured out for the _next_ election, not this one, so that we can get someone elected fairly quickly. Thoughts?

**Comment by nebrius** [comment]
After giving it some thought, I'm announcing my intention to run for this position 😄

**Comment by hackygolucky** [comment]
So do we need to open a separate issue regarding the shortened term for the chairperson or just chat about it as a second bullet for this issue in question?

**Comment by bnb** [comment]
@williamkapke What further steps are needed in this, now that @nebrius has been elected unopposed?

**Comment by williamkapke** [comment]
Just a PR to the README indicating that he holds that honor!

In the TSC repo, I made the members list have pictures (just to jazz things up), I made everyone alphabetically ordered, BUT put the Chair/Director at the top noting that position:

![image](https://cloud.githubusercontent.com/assets/739813/26020838/8f5fcf2a-3738-11e7-9e42-85fb779c58f1.png)

**Comment by bnb** [comment]
@williamkapke Done! I tried converting the list to a table, but Markdown formatting hates my attempts at tables 😞 

Here's the PR: https://github.com/nodejs/community-committee/pull/58

**Comment by nebrius** [comment]
PR was merged, so I'm going to go ahead and close this issue. Feel free to reopen if there's any outstanding work still to be done.
