### ISSUE TITLE
I would like to take part in development of node

### ISSUE THREAD

**Issue by chirag8642** [nodejs/community-committee#304]
I am interested in taking part in node js development.

**Comment by WaleedAshraf** [comment]
Hi @chirag8642! That's great. 🎉 
You can start with [Getting Started](https://github.com/nodejs/getting-started) guide. There is plenty of information available. If you still have any question, feel free to reach here. 👍

**Comment by Tiriel** [comment]
Howdy!

I don't know if you're still looking since this has been open for quite a long time, but if you're looking for taking part in the development of Node.js core, I'd suggest looking in the [nodejs/node repo and look at the good first issues](https://github.com/nodejs/node/labels/good%20first%20issue).

If you're looking to take part in the development of the community, on the other hand, you've come to the right place, but we need more context on what you'd like to do.

I'm going to close this for now as it's been a while, but do feel free to reopen, you are perfectly welcome!
