### ISSUE TITLE
We need more swag 😎

### ISSUE THREAD

**Issue by AdriVanHoudt** [nodejs/community-committee#332]
I am opening this issue as a follow up of https://twitter.com/Ben_Tiriel/status/1004374678335614976.
I think the community wants way more swag then the occasional sticker/t-shirt/mug at a conference and if the foundation can benefit from that I can only see a win win.
I found https://node-js-community-store.myshopify.com/ but not sure if that is legit/maintained or what the general status is of it.

The question raised in the twitter thread is mainly surrounding the trademark of Node.js and the logo.
* Is there anyone who knows what the status surrounding this is and what the steps would be to, for example, make a mug with the logo available?
* If https://node-js-community-store.myshopify.com/ is legit it would benefit from an update to make it look more legit and to maybe advertise it more.
* If anyone has ideas about the type of swag, shoot!
	* Mug
	* Stickers (I think it is the same as a decal but not sure)
	* More t-shirt designs/colors
* As a EU citizen I would greatly appreciate a EU store without massive/needless shipping

(First issue here so let me know if I did anything wrong :D)

**Comment by Tiriel** [comment]
Hey!

Thanks for opening the issue! Obviously, I'm all in for more swag. But as discussed, we have licensing issues.

So I guess the first step would be to raise a question to the Foundation: Can we ask for more diverse swag, and if yes, would there be a proper process to have things running smoothly?

I know that the Security WG is [also discussing swag](https://github.com/nodejs/security-wg/issues/293), and quite frankly, I think that's a really important part of community building.

I think the people most likely to have information on the process here are @bnb  and @hackygolucky 
Cheers!

**Comment by amiller-gh** [comment]
The @nodejs/badges WG was also talking swag – we'll need to chat about licensing and resale at some point.

**Comment by ZibbyKeaton** [comment]
Background: This store is completely legit and is actually run by the Node.js Foundation. We launched it a few years ago and had to change platforms a bit because of some hiccups. It's fallen under the NF marketing team's "jurisdiction" and I usually only use the store when I have collaborators, Node.js meetup groups, student groups and Node.js-centric conference folks ask me for free swag  - see [here](https://github.com/nodejs/community-committee/issues/228). 

That being said, we understand that what's in the store and how the store is presented really needs to be refreshed, and have also been having this convo internally as well. @ladyleet is currently focused on an overall store refresh and is actually the best person to talk to about this.

**Comment by Tiriel** [comment]
@ZibbyKeaton Awesome, thanks for the background!

I think there is a double point to be raised here though.
It's not only that we'd like newer items (most items present in the store are still cool imo, we'd just like specific ones), but it's also that some of us would like a bit more access to the swag, to be able to distribute them.
I'm mainly thinking here about the idea of sending swag to most active Security WG contributors, or such ideas that rose lately.

This would require that at least the top level committees have some measure of control, I think, but I may be mistaken. I'd gladly take this issue to the CommComm, but first, we need to know if it would be doable from a Foundation point of view I guess.

@ladyleet, do you think that something along those lines could be discussed? Or would it be completely out of the way?

**Comment by AdriVanHoudt** [comment]
Nice to know that @ladyleet is working on the new site, if you need some help I am willing to. ✨
Ideally the new store would also ship from the EU, not sure if that is being talked about as well?
Should the Node Foundation promote the store more (internally/externally)?
There must be a current process to obtain the right/clearance to use the node logo, otherwise where did those mugs come from, does anyone know this process?

**Comment by ZibbyKeaton** [comment]
I will let @ladyleet address your questions @Tiriel, but this is something that is going into our general strategy around the swag store, i.e. how best to implement a process to address community requests/needs as I believe a few members of the Security Working Group have asked Tracy about this.

I think I can address most of your questions @AdriVanHoudt:

We will not be doing a new store/new site as of now. We've tested a few sites/services and this one is the best that we've used and we use it across Linux Foundation projects. One of the main reasons we chose this company and service was because they have really reasonable shipping and handling overseas. So if you are based in EU, no problem, you can get swag. I've also shipped swag to Australia and Africa :) I think trying to create an entirely new site/service would not be the best use of our efforts TBH. 

The Node.js Foundation does and has promoted this store externally. It's on our website and I share it on Twitter from time to time. I think it would probably get a lot more eyeballs if it was on the nodejs.org because that drives a lot more traffic than the Node.js Foundation's website (we had it there for awhile, but can't find it now). If you want to propose that it be added via the website working group feel free.

You can also find the trademark policies on nodejs.org and on the Node.js Foundation page. Find here: https://nodejs.org/en/about/trademark/ and here: https://nodejs.org/static/documents/trademark-policy.pdf This should give you the direction needed to use the Node.js logo.

Hopefully this was helpful 😀

**Comment by jakeNiemiec** [comment]
>Copyright Joyent, Inc. and other Node contributors. All rights reserved.
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to
deal in the [software **and associated documentation files**] without restriction, including without limitation the
rights to use, copy, **modify**, merge, publish, **distribute**, sublicense, and/or
**sell** copies of the [software **and associated documentation files**]...

I am not a lawyer, but it would seem that anyone could distribute/sell any assets included in the documentation as long as you provide a paper licence with the merch 🤔. Example: https://github.com/nodejs/node/blob/master/doc/osx_installer_logo.png

**Comment by ladyleet** [comment]
Hey all! Yes - @annmarietonog and I are both working on this.

This week we finished a site redesign to make it a little nicer and are getting approval for new swag as well. I think both of these will be great.

We do promote the Node store but we will promote it more once we have new swag.

We are working on getting other designs and cooler stuff in the store as well. Some folks have reached out to want to help with some design stuff related to the new swag, so if you have ideas you can drop myself and Ann Marie a line at annmarie@nodejs.org and ladyleet@nodejs.org. 

As @ZibbyKeaton said the store does ship to EU so there should be no issues there.

In terms of working groups getting swag for contributors, we do have a budget set aside for this so send an email to us and we can figure things out - whether it's providing a code for folks to pick from the store or something else.

<3 Hope I answered all the questions?

**Comment by AdriVanHoudt** [comment]
Those links are very helpful, it seems that I would be allowed to print my own stickers for personal use if I want to 👌 
I do look forward to the new website and swag 🔥 and glad that shipping to the EU is not gonna cost me more then the items themselves :D
I think adding a link to the new store on nodejs.org would be very nice! Do I open an issue on the website WG or would it be better to wait for the new version to come online?

**Comment by ZibbyKeaton** [comment]
Whatever you want to do @AdriVanHoudt - the URL won't change. I'll probably make more of a splash on social when we have the re-design and more items in the store, so if you are leaning towards one or the other, I might go with post redesign.

**Comment by AdriVanHoudt** [comment]
Sounds good!

**Comment by bnb** [comment]
Going to close this for now since it seems like there's not been much recent discussion. Feel free to re-open if necessary 👍
