### ISSUE TITLE
Q&A with Jem Bezooyen @jembijoux: CommComm Chairperson Election

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#369]
CommComm Chairperson Q&A session for Jem Bezooyen @jembijoux! 

Feel free to drop your questions for @JemBijoux here as comments.

# Candidate Statement

As the first portion of my statement, I’ll note that the reason I self nominated was because I wanted to see someone in the space who is both appropriately passionate for seeing the committee succeed and has a keen interest in the duties of this role. It’s really awesome to see the four other names that have stepped up to the plate on this. I can honestly tell you that I would endorse almost any of the others.

Ultimately I’m not worried about whether or not I’m elected as Chairperson (this time around). I am just very much excited to have the opportunity. I can always be of tremendous value in other roles and intend to continue finding opportunities to lend my strengths either way. While I would relish the opportunity to serve the community at this level, I also acknowledge that my examples to prove myself so far might be limited.

A secondary reason for putting my name into the ring is that I enjoy many of the duties listed in the “expected responsibilities”. Creating agendas is somewhat complementary to taking notes, and I’m a strong advocate for remote communication strategies (running remote meetings and ensuring participants are feeling heard). I think I would be more than capable of facilitating communication on all the required channels, though acknowledge that my connections and context are newer than some other candidates.

Consider me excited to help at whatever level possible. I look forward to working with all of you on working groups, at N+JSI, and through events to come!

**Comment by bnb** [comment]
What are the current rough edges that you see with the Node.js Community Committee, and what would your ideal solutions be to those rough edges in a years' time?

**Comment by JemBijoux** [comment]
# Candidate Statement

As the first portion of my statement, I’ll note that the reason I self nominated was because I wanted to see someone in the space who is both appropriately passionate for seeing the committee succeed and has a keen interest in the duties of this role. It’s really awesome to see the four other names that have stepped up to the plate on this. I can honestly tell you that I would endorse almost any of the others.

Ultimately I’m not worried about whether or not I’m elected as Chairperson (this time around). I am just very much excited to have the opportunity. I can always be of tremendous value in other roles and intend to continue finding opportunities to lend my strengths either way. While I would relish the opportunity to serve the community at this level, I also acknowledge that my examples to prove myself so far might be limited. 

A secondary reason for putting my name into the ring is that I enjoy many of the duties listed in the “expected responsibilities”. Creating agendas is somewhat complementary to taking notes, and I’m a strong advocate for remote communication strategies (running remote meetings and ensuring participants are feeling heard). I think I would be more than capable of facilitating communication on all the required channels, though acknowledge that my connections and context are newer than some other candidates.

Consider me excited to help at whatever level possible. I look forward to working with all of you on working groups, at N+JSI, and through events to come!

## Office Hours

As a side note: I’d love to extend an open invite to anyone who’d love to ask me questions or talk through anything. Even just to get to know some of you better! I might not have answers to everything, but I’d really dig learning your opinions and getting any insights you’re open to sharing. I’ll have open office hours through out the weekend, and tomorrow (Friday) between 7pm - 11pm PDT.  (Drop a request here or ping me on twitter @jembijoux)

**Comment by amiller-gh** [comment]
Closing because elections are over ❤️
