### ISSUE TITLE
Q&A with Dan Shaw @dshaw: CommComm Chairperson Election

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#372]
CommComm Chairperson Q&A session for Dan Shaw @dshaw! 

Feel free to drop your questions for @dshaw here as comments.

*CANDIDATE STATEMENT*

Node.js has always been a community-driven project and it has been wonderful seeing the Community Committee grow and get even better at serving and connecting that community to the Node.js project and the Node.js Foundation.

It would be an honor to serve as chair and would serve dilutifily. Since we are all blind candidates, I am actually going to endorse Adam Miller.

@amiller-gh has proven ability to lead and facilitate in CommComm initiatives like @nodejs/website-redesign, badges, as well as actively collaborating, coordinating and synthesizing context for all @nodejs/community-committee. I believe that Adam has the best ability and availability to serve as our next Chair.

**Comment by dshaw** [comment]
_CANDIDATE STATEMENT_

Node.js has always been a community-driven project and it has been wonderful seeing the Community Committee grow and get even better at serving and connecting that community to the Node.js project and the Node.js Foundation.

It would be an honor to serve as chair and would serve dilutifily. Since we are all blind candidates, I am actually going to endorse Adam Miller.

@amiller-GH has proven ability to lead and facilitate in CommComm initiatives like @nodejs/website-redesign, badges, as well as actively collaborating, coordinatating and synthesizing context for all @nodejs/community-committee. I believe that Adam has the best ability and availability to serve as our next Chair.

**Comment by amiller-gh** [comment]
I don't know what to say Dan! All I know is I firmly believe that the CommComm would be lucky to be in **_any_** of the nominee's hands – especially yours. Thank you for the endorsement ❤️

**Comment by dshaw** [comment]
@amiller-gh 100% agree. We are blessed to have so many active, able and thoughtful members and individuals willing to take on this responsibility.

**Comment by amiller-gh** [comment]
Closing because elections are over ❤️
