### ISSUE TITLE
Request to move nodejs/education under CommComm

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#46]
Currently, the Education repo for Node.js is floating in lalaland, unchartered. I'd like to officially move this under CommComm scope. 

Since there wasn't a charter and there hasn't really been involvement from @nodejs/tsc from generally, things in the Node.js org fall under their scope, do I need to ask the TSC to move this? Otherwise, I request the CommComm votes on this in the next meeting.

Request to TSC [here](https://github.com/nodejs/TSC/issues/282).

**Comment by williamkapke** [comment]
The education repository is listed under the TSC's scope as an [adjacent projects](https://github.com/nodejs/TSC#adjacent-projects), so- the members of that effort/team will need to ask them to relinquish the scope.

**Comment by nebrius** [comment]
Since this isn't a chartered WG, anyone can request to move the repo to the TSC since (procedurally speaking) the only group that needs to weigh is the TSC. In practice you should strive to reach consensus with the team of course, so I'd recommend opening an issue in the education repo first just to make sure there are no objections. Then we can either tag that issue as `tsc-agenda`, or open a new one in the TSC repo and tag it there (both approaches work fine, our meeting scripts pick up tags across all node repos when creating agendas).

**Comment by nebrius** [comment]
Issue opened in education to make sure there are no objections at https://github.com/nodejs/education/issues/33.

Since we're waiting on education, I'm removing the `cc-agenda` label for now.

**Comment by hackygolucky** [comment]
@nebrius I'm not sure how long of a window we should wait, since we don't really have a team that was particularly active in GitHub(the advisory group never seemed to pick up on it and instead stayed communicating via email)

**Comment by nebrius** [comment]
@hackygolucky do you feel like everyone who would want to have a say has had a say? If so, I think we've done everything we need to do consensus wise with education and we're ready to make a formal decision in CommComm and we can re-add the `cc-agenda` label at any time.

**Comment by bnb** [comment]
@hackygolucky Did we finalize this? I don't see nodejs/education in the README.md in CommComm, and the TSC issue seems to be a non-issue.

**Comment by bnb** [comment]
Looks like this landed in #191 - going to close it now 👍
