### ISSUE TITLE
Code & Learn in a Box

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#503]
Discussed in today's meeting, I brought up one of the persistent issues I've seen at Code and Learn events: network saturation and getting people set up  with the nodejs/node git repo + the tools they need to actually build node.

In my experience this results in network saturation and a not-optimal experience for everybody. Every event I've been at ends up with a few people sharing stuff via USB or AirDrop, with attendees taking a non-trivial amount of time to get set up before they can begin to think about writing tests, contributing to docs, or whatever other tasks they were assigned.

At the NodeConf Colombia event, I started trying to think about how we could help make this easier. In today's meeting, I proposed using a local server on a Raspberry Pi. @amiller-gh suggested that he's recently been working on a local discoverable server for people who are on the same network.

I'd like to propose that we start a Community Committee technical project focusing on building out some kind of local server that we can use as Code & Learn in a Box to help address these issues.

**Comment by bnb** [comment]
cc @addaleax and @Trott – I don't want to take away from your work on Code and Learn, so would very obviously want your permission for this since Code and Learn is not technically a WG/initiative/team of the project.

**Comment by Trott** [comment]
We've explored options like this in the past and concluded it wasn't worth the effort, but that doesn't mean it's not worth looking at again. (Especially because I can't remember *why* we concluded that.)

From my perspective, we've had great success with a far simpler solution: Email all attendees well ahead of time with the instructions for cloning the repo and installing prerequisites and telling them they must do it before the event. (Sure, they don't really have to, but just tell them it's a requirement.) 

Having @bengl burn a day or two getting everything on USB keys is helpful too, but it's really all about sending out an email early TBH.

Relevant aside: I'd like to see us do fewer and/or smaller Code + Learn events. I feel like there are fewer trivially good-first-issues in core than ever before. This makes Code + Learn harder, and encourages PRs that are on the debatable-churn side of things. What would be wonderful is to see Code + Learn applied to other aspects of Node.js (like the website) or to other projects. But when we've proposed that in the past, people talk a big game about being excited to do that, and then it falls flat. I'd like to see us find other ways to engage the community than Code + Learn. It was great. But we need other mechanisms.

**Comment by addaleax** [comment]
Yeah, the NodeConf Colombia event was great but it lacked a lot of preparation. Before the event, I had mistakenly assumed that it had been set up closely together with an active collaborator, with things like informing participants of requirements and preparing tasks in advance having been taken care of in some way. The solution of emailing participants with instructions for getting set up worked pretty well in the past, imo.

**Comment by codeekage** [comment]
I really don’t know the direction this issue took over time, but this something I see being a good OKR for next year.`Community Technical Initiative` And see how we can make people organising Node events get folks (attendees) on board faster and make contributions too.

**Comment by bnb** [comment]
I am going to close this for now with the possibility of re-opening in the future, since it seems that at present we don't really have the necessary critical mass in terms of ability to continue running Code & Learn events to justify something like this. Happy to have the closing reversed should that change!
