### ISSUE TITLE
Community Committee Chairperson Self Nominations

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/community-committee#518]
### It's nomination time for the Chairperson of Community Committee.

Please submit your self-nominations to [this form](https://forms.gle/bBgRwjLxRWAGkqJY8) by *Monday. August 26 at 11:59pm PT*. Nominations will be published after the date passes so that candidates can be considered for election.  Please do not publicly share you are running prior to this date. This allows folks to consider contributing as chair without the added distraction of competition.

> The CC will elect from amongst voting CC members a CC Chairperson to work on building an agenda for CC meetings [...] The CC shall hold annual elections to select a CC Chairperson [...]; there are no limits on the number of terms a CC Chairperson [...] may serve.

Expected responsibilities include but are not limited to:
- Create each meeting's agenda. 
- Create the event and make sure it is live-streamed in YouTube. 
- Chair and facilitate each meeting. It is the chairperson's responsibility to ensure that the meeting stays on track, sticks to the agenda, and finishes within the allotted time.
- Collaborate with the CPC Reps
- Collaborate with the TSC Chair
- Coordinate efforts in shared repos, as listed in Admin

All Community Committee active members are eligible to self-nominate. If you are having trouble with voting, please email adam@pages.me.

## Nominated candidates:
- Tierney Cyren (@bnb)

**Comment by hackygolucky** [comment]
@amiller-gh @bnb Would it be possible for you to share a bit more about the time commitment you have found useful/necessary to be effective in the role? Esp things like standing weekly/monthly meetings and the # of ad hoc ones you found yourself in? I think it's helpful for folks to understand how to be helpful and to manage expectations with employers.

**Comment by bnb** [comment]
I personally found it ended up being about 20/hours a week on a normal week, which was largely during work hours since that was something that my time as a Developer Advocate at NodeSource enabled me to do.

I was attempting to attend as many new Initiative meetings as possible to help them get off the ground and running, in addition to consistently answering 1:1 pings on various platforms (Slack, Twitter DM were the primary ones, I don't recall the others but there were a few people who preferred other platforms. and having discussions about concerns / answering questions that were sometimes rather in-depth.

Outside of that, there were normal responsibilities including attending *every single* CommComm meeting and following through on leadership tasks such as working with other project leadership (at the time, TSC Chairperson, TSC & CommComm Directors) on certain massively impactful decisions (one of the biggest that I worked on was the beginnings of the merger of the Node.js Foundation and JS Foundation, into OpenJS Foundation).

I believe the number of regular meetings I quoted previously was something like 6-8, with an additional 4-6 meetings ad hoc meetings weekly.

Additionally, it's worth noting that you will have to care about the things nobody else does. You will have to deal with all the things that are seemingly trivial but must be completed – charter/governance processes, updating and maintaining certain aspects of how the group works, maintaining repos that nobody else works on, closing stale/old issues periodically, maintaining Org membership for individuals under the CommComm and its initiatives, responding to random one-off requests like the recent one to unarchive nodejs/evangelisim and nodejs/website-redesign so issues could be unlabeled, and so on.

I would highly recommend having _at least_ 20 hours a week – including _at least_ 10 during working hours – that you can 100% dedicate **for the next year** to being chairperson if you're considering applying.

**Comment by bnb** [comment]
@amiller-gh also, quick question: how are you storing the information in the form? We had a discussion about this last time around and were very intentional in our approach – I believe we opted out of using a form for very specific reasons.

**Comment by amiller-gh** [comment]
@bnb – its in a private sheet in google drive. I duplicated the form used last year.

At its peak, I found it to be a similar time commitment. I attended fewer individual initiative meetings because they were largely self-sufficient (good job @bnb!), so in my experience it was a similar 14-18 hours a week. 

Agreed that it is **very** important to have time at work to dedicate to this. Personally, I had this flexibility for the majority of my tenure, but the past couple months I haven't had as many cycles during work to dedicate, and have struggled to keep up.

**Comment by amiller-gh** [comment]
@nodejs/community-committee Link to vote was just sent out. You should have it in your inboxes at the address listed in the CommComm README. You have until Saturday EOD to cast your vote for Tierney, or “No Confidence”. Please let me know if you did not receive it!

**Comment by amiller-gh** [comment]
@nodejs/community-committee Polling is closed as of Saturday night and I'm happy to announce that...

(drum roll 🥁🥖)

@bnb is now Community Committee chairperson! Excited to see what this next year brings ❤️

**Comment by codeekage** [comment]
Closing this issue as we have a new a CommComm chair
