### ISSUE TITLE
Self Nomination

### ISSUE THREAD

**Issue by saulonunesdev** [nodejs/community-committee#614]
Hello,

in order to facilitate/help the @nodejs/mentorship and others Working Groups/Initiatives I would like to self nominate for CommComm

Thanks

@nodejs/community-committee  Please add **agenda** label ^^

**Comment by ahmadawais** [comment]
Saulo you'll be an excellent addition. +1 from my side.

**Comment by joesepi** [comment]
I wholeheartedly approve.

**Comment by bnb** [comment]
We don't normally +1 in comments since this would be a CommComm vote and not something we comment our +1/+0/-1 in comments, but that is apparently something we're currently doing in this thread.

Given the above, I'd like to share that based on my observations in nodejs.dev and what's currently happening with that work, I'm -1. Happy to go into more detail privately if needed.

**Comment by saulonunesdev** [comment]
I withdraw my nomination.

Thanks @ahmadawais @joesepi @bnb
