### ISSUE TITLE
I want to join Node.js Community Committee

### ISSUE THREAD

**Issue by viveksharmaui** [nodejs/community-committee#616]
Hi ! 
My name is "Vivek Anand" , i'm using node.js for around 3 years .
I wants to join node.js community committee and i want to work on node.dev and node.org and attend meetings.
If you wants to invite me as it will be great.

**Comment by bnb** [comment]
You are more than welcome to go do that work in github.com/nodejs/nodejs.dev and github.com/nodejs/nodejs.org, which ends up leading to becoming a part of the Community Committee. You don't need to be a member of the Community Committee to contribute. I'd recommend heading over to those repos and tackling issues and submitting PRs 👍 

Going to close for now since the request of the issue is not how membership in the committee works, and the above instructions are the path to that.

**Comment by viveksharmaui** [comment]
Thanks for instructions 👍
I will contribute in node.dev and node.org and then join community committee.

**Comment by viveksharmaui** [comment]
@bnb I'm now Contributor of node.dev and very interested to become node js community committee member.
