### ISSUE TITLE
Create Contributing Guide

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#69]
As mentioned in last week's CommComm meeting, I've had several people come and ask me how to get involved. I've realized that there's no actual instruction on how, where, or what people can get involved with. 

I'd like to ask that we create a contributing guide as a place to get started and point people to when they ask how they can get involved.

**Comment by nebrius** [comment]
> I've realized that there's no actual instruction on how, where, or what people can get involved with.

Probably because there's no process to write instructions for yet, these processes are uncreated, not undocumented ;-)

We have a bit of a chicken and an egg situation right now given that there aren't any working groups/teams under us, but eventually it will basically be "find a working group or team that's been created to work on what you want to work on and take a look at their instructions for joining. If a WG/team doesn't exist, file an issue with CommComm requesting a repo be created for you."

**Comment by nebrius** [comment]
FYI we currently have one team under CommComm currently:

https://github.com/nodejs/nodejs-collection

**Comment by bnb** [comment]
PR has been opened: https://github.com/nodejs/community-committee/pull/75

**Comment by benjamingr** [comment]
Related: https://github.com/nodejs/CTC/issues/147

**Comment by pup** [comment]
closing since #75 is in
