### ISSUE TITLE
Node.js User Feedback initiative

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#96]
I was chatting with @mhdawson this week, and he expressed the need for forming Node.js user feedback mechanisms so that we as a project can be improving on a much shorter timeline from said feedback that we've gotten from work such as our annual user survey. This also allows us to get perspectives from a much wider audience than we generally get in our committee meetings(TSC, CommComm, CTC, etc). We'd discussed this as an area of scope with the CommComm when it is was formed, but no one has kicked off a formal 'let's do this'. 

So let's do this!

Suggested mediums for user feedback:
- surveys: much smaller, more tightly scoped, and can be shared in a shorter timeframe than the annual survey.
- user focus groups: gathering users at events such as meetups, confs, and internal meetings at companies that allow us to observe, gather data, and synthesize for actionable change.

Please suggest other forms of user research formats that could be helpful. If you know any folks with user research experience, it would be awesome to ping them and have them chime in here. After we establish _types_ of formats we can be doing, we'll open individual issues about the how-to for approaching implementing each of these.

**Comment by mhdawson** [comment]
The two options you have are the best 2 I can think of as well.  One more that may or may not be uesfull is to see if any of the existing foundation members fall into the category of "users"s versus vendors and if so reach out to them to see if they are willing/capability of participating in capturing user feedback.

**Comment by nebrius** [comment]
Would this be something for @nodejs/evangelism to take a look at? I suspect this could fall under their domain.

**Comment by lordKnighton** [comment]
@hackygolucky Sounds like a plan.

 And I think https://nodejs.org/en/ wouldn't be a bad portal to get some feedback.

**Comment by bnb** [comment]
Great idea. Coming from an Evangelism perspective, it's really nice to have some collateral to be able to easily share on social for feedback on technical issues.

@nebrius definitely could be a good fit for the Evangelism WG. Defining some questions, length, and structure are a 👌 way to start out.

**Comment by mhdawson** [comment]
I'm wondering how we define next steps so that we can move this forward.  @bnb do think somebody from the Evangelism and lead the effort ?

**Comment by gtewallace** [comment]
In addition to promoting this on the web site and via evangelism channels, in the annual survey we ask respondents to provide their email if they would be willing to be contacted by the Node.js Foundation for additional questions. @hackygolucky could create an alias with these folks and send them an email - or we can do out of mailchimp. there are around 250 people in the list who provided email addresses saying they are OK being contacted.

**Comment by hackygolucky** [comment]
For the Community Committee to be able to really act on anything, getting this feedback/data is a core responsibility of the CommComm members themselves and the Individual Membership Directors.  

>  Each Individual Membership Director is responsible for soliciting feedback and data that represents the wishes of other individual members and the community at large. [source](https://github.com/nodejs/community-committee/blob/master/GOVERNANCE.md#section-9-roles)

Evidence-based decision-making tends to produce better outcomes thanks to getting the perspectives needed to act. Evangelism is a vehicle for sharing out what we are doing through communications, social media, etc. 

Why not have a member of the CommComm directly volunteer to do this work? To some extent, CommComm itself also needs to be producing output, which is why I filed this issue. We certainly need to figure out a way to project manage this type of work , but I don't think delegating work is getting it done. We've got a ton of open issues right now that aren't getting tackled. 

My suggestion for next steps:
- File an issue for a planning meeting where the initiative can be hashed out and a project plan is written. The Individual Directors should be present. In this meeting:
  - choose a survey medium(SurveyMonkey, Google forms, etc.)
  - make a list of current small surveys/feedback we need and create a schedule for these
  - document how folks could request a survey question/set(likely issue filing or a PR flow) so we could continue to add to the survey schedule moving forward
  - Identify relevant gatherings for holding user focus groups: choose a few places as a first step that people IN the meeting will be present at and could hold a meeting, collect feedback, and synthesize for publish.
- Publish User Feedback Initiative plan, implement, and iterate.
- coordinate with the Evangelism WG to share the surveys via their platform using the schedule

**Comment by dshaw** [comment]
@hackygolucky I met with @williamkapke and @mikehostetler. In terms of availability and interest, it looks like it will fall on me to lead this initial bootstrap phase with their support. I'm game, but am going to seek some very explicit permission first since this is a massive undertaking.

1) Can I even lead this effort since I am only a CommComm Observer?
2) I would like to start by focusing on establishing end user communications channels first with tooling and technique as a secondary consideration.
3) Who are the individuals who would need to sign-off to ensure that handoff of this initiative is explicit and that none of the original objectives are lost? As far as I can tell, that would be @hackygolucky and @mhdawson.

Many folks know me and I have been an active community member for a very long time, but I am actually not well versed in the norms and processes of Node.js here on GitHub. I welcome all of your feedback and am intentionally trying to follow new user paths and behavior to help model process and governance improvements. 🙏

**Comment by dshaw** [comment]
## Notes from 2017-10-26 breakout meeting on #96

We discussed bootstrapping a new group in the Node.js CommComm focused on User Feedback and Outreach.

@dshaw is spearheading the effort with active contributions to the scoping efforts from @williamkapke, Individual Member Director of the Node.js Foundation, and @mikehostetler, Chicago Node.js/JS Community Leader.

We have identified key areas of interest for each of the bootstrap team:
@dshaw - Enterprise Users
@williamkapke - Individual Members of the Node.js Foundation
@Mike Hostetler - Chicago Node.js/JS Community - with the intention to see how solving local needs in Chicago can serve as a model for other local communities

Since there’s a pretty massive potential scope of effort with this project, @dshaw is going to seek explicit permission first. This goes against the current norms of the Node.js project, but is vital to the bootstrap team to be able to justify the investment of time and effort.

All are welcome and will always be welcome. At this time we are explicitly seeking collaborators who can dedicate 5+ hours/month to get this effort off the ground and assist in project scoping. If you are engaged with community in any of the 3 key interest areas: Enterprise, Individual Membership, Local Communities and have interest and availability, please join us.

**Comment by hackygolucky** [comment]
[Google Doc from the initial meeting](https://docs.google.com/document/d/1NOQsC-nyYz75IMJVitzTwuCYgLWWLhWaSvWRPveiumU/edit) that @bnb and @mhdawson and I had on this. Glad y'all are hopping on this!

**Comment by dshaw** [comment]
I wanted to say thank you to @hackygolucky @mhdawson @bnb and @williamkapke for all the support in working through this and getting this effort off the ground. 🙏

**Comment by bnb** [comment]
@dshaw @hackygolucky since there's been a significant amount of work done on the User Feedback Initiative outside of this issue, can we close this issue?

**Comment by mhdawson** [comment]
I'd be +1 on closing this and tracking through issues in the user-feedback repo.

**Comment by bnb** [comment]
Closing 👍
